-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
local lib = aic.custom_dialog
local l10n = aic.l10n[setting.locale]
local sc_list = l10n.ui.sc_list
local dialog = l10n.dialog
_LoadImageFromFile('image:'..'cdbg04a','cdbg04a.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'cdbg04b','cdbg04b.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'charge','charge.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Maribel_face','Maribel_face.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Renko_face','Renko_face.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Hiffu_face','Hiffu_face.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Aya_face','Hiffu_face.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'sp1_1_bg','sp1_1_bg.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'sp1_2_bg_1','sp1_2_bg_1.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'sp1_2_bg_2','sp1_2_bg_2.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'sp1_3_bg_2','sp1_3_bg_2.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'sp1_3_bg_1','sp1_3_bg_1.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'sp1_4_bg_1','sp1_4_bg_1.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'sp1_4_bg_2','sp1_4_bg_2.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'photo_dark','photo_dark.png',true,0,0,true,0)
_LoadImageFromFile('image:'..'photo_light','photo_light.png',true,256,192,true,0)
_LoadImageFromFile('image:'..'dark_fog','dark_fog.png',true,0,0,false,0)
LoadAniFromFile('ani:'..'crow','crow.png',true,4,1,4,16,16,false)
LoadAniFromFile('ani:'..'beer','beer.png',true,4,1,4,16,16,false)
LoadAniFromFile('ani:'..'bu_bird','bu_bird.png',true,3,1,8,5,5,false)
_editor_class["dialog_boss_name"]=Class(_object)
_editor_class["dialog_boss_name"].init=function(self,_x,_y,name1,name2)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_TOP+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.x = 50
    self.y = -50
    self.alpha = 0
    lasttask=task.New(self,function()
        local x0=(self.x)
        do
            local _beg_al=0 local al=_beg_al local _end_al=255 local _d_al=(_end_al-_beg_al)/(30)
            local _beg_x=x0 local x=_beg_x local _end_x=x0+30 local _d_x=(_end_x-_beg_x)/(30)
            for _=1,30 do
                self.x=x
                self.alpha = al
                self.rot = rot
                task._Wait(1)
                al=al+_d_al
                x=x+_d_x
            end
        end
    end)
end
_editor_class["dialog_boss_name"].render=function(self)
    DrawText('main_font_zh_cn', self.name1, self.x, self.y, 1,
        Color(self.alpha, 182, 109, 112), Color(self.alpha, 0, 0, 0), 'centerpoint')
    DrawText('main_font_zh_cn', self.name2, self.x, self.y - 30, 1.75,
        Color(self.alpha, 255, 255, 255), Color(self.alpha, 177, 42, 44), 'centerpoint')
    self.class.base.render(self)
end
_editor_class["NB_Portrait_AI"]=Class(_object)
_editor_class["NB_Portrait_AI"].init=function(self,_x,_y,img,s,dx)
    self.x,self.y=_x,_y
    self.img=img or "image:Aya_face"
    self.layer=LAYER_PLAYER-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    s=s or 0.05
    dx = dx or 0
    self.hscale=s
    self.vscale=s
    self.omiga=0---0.05
    (self).x,(self).y=192,96
    _object.set_color(self,"",0,255,255,255)
    local sn=(3)
    lasttask=task.New(self,function()
        do
            local _beg_ia=0 local ia=_beg_ia local _end_ia=255 local _d_ia=(_end_ia-_beg_ia)/(30-1)
            local _beg_isc=s local isc=_beg_isc local _end_isc=s+0.1 local _d_isc=(_end_isc-_beg_isc)/(30)
            for _=1,30 do
                _object.set_color(self,"",ia,255,255,255)
                self.hscale = isc
                self.vscale = isc
                task._Wait(1)
                ia=ia+_d_ia
                isc=isc+_d_isc
            end
        end
        task._Wait(60)
        do
            local _beg_ia=255 local ia=_beg_ia local _end_ia=0 local _d_ia=(_end_ia-_beg_ia)/(30-1)
            for _=1,30 do
                _object.set_color(self,"",ia,255,255,255)
                task._Wait(1)
                ia=ia+_d_ia
            end
        end
        _del(self,true)
    end)
    lasttask=task.New(self,function()
        do
            local _beg_iy=96 local iy=_beg_iy local _end_iy=0 local _w_iy=0 local _d_w_iy=1/(30-1)
            local _beg_ix=192 local ix=_beg_ix local _end_ix=dx local _w_ix=0 local _d_w_ix=1/(30-1)
            local i=1 local _d_i=(1)
            for _=1,30 do
                (self).x,(self).y=ix,iy
                if i>=60-sn then break end
                task._Wait(1)
                _w_iy=_w_iy+_d_w_iy iy=(_beg_iy-_end_iy)*(_w_iy-1)^2+_end_iy
                _w_ix=_w_ix+_d_w_ix ix=(_beg_ix-_end_ix)*(_w_ix-1)^2+_end_ix
                i=i+_d_i
            end
        end
        self.vx,self.vy=self.dx,self.dy
        task._Wait(sn)
        task._Wait(30)
        _set_a(self,0.05,180,false)
    end)
end
--[[ Code by 夜雀的歌声,Arranged by Muki
]]
_editor_class["aya_charge"]=Class(_object)
_editor_class["aya_charge"].init=function(self,_x,_y,type, t, r, g, b)
    self.x,self.y=_x,_y
    self.img="image:charge"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    if type == 'in' then
        _object.set_color(self,"mul+add",0,r,g,b)
        self.hscale = 5
        self.vscale = 5
        lasttask=task.New(self,function()
            PlaySound("ch02",0.1,self.x/256,false)
            do local a,_d_a,b,_d_b=(3),(-3/t),(0),(255/t) for _=1,t do
                _object.set_color(self,"mul+add",b,r,g,b)
                self.hscale = a
                self.vscale = a
                task._Wait(1)
            a=a+_d_a b=b+_d_b end end
            _del(self,true)
        end)
    else
        _object.set_color(self,"mul+add",255,r,g,b)
        self.hscale = 0
        self.vscale = 0
        lasttask=task.New(self,function()
            PlaySound("enep00",0.1,self.x/256,false)
            do local a,_d_a,b,_d_b=(0),(3/t),(255),(-255/t) for _=1,t do
                _object.set_color(self,"mul+add",b,r,g,b)
                self.hscale = a
                self.vscale = a
                task._Wait(1)
            a=a+_d_a b=b+_d_b end end
            _del(self,true)
        end)
    end
end
_editor_class["aya_bg_sp_1"]=Class(_spellcard_background)
_editor_class["aya_bg_sp_1"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:sp1_1_bg",false,0,0,0,0,0,0,"",0.5,0.5,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["aya_bg_sp_2"]=Class(_spellcard_background)
_editor_class["aya_bg_sp_2"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:sp1_2_bg_2",true,0,0,0,0,-0.2,0,"mul+alpha",0.25, 0.25,
        function(self)
            self.task={}
            self.a = 50
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:sp1_2_bg_1",false,0,0,0,0,0,0,"mul+alpha",0.5,0.5,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["aya_bg_sp_3"]=Class(_spellcard_background)
_editor_class["aya_bg_sp_3"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:sp1_3_bg_2",true,0,0,0,-0.2,0.2,0,"mul+alpha",0.25, 0.25,
        function(self)
            self.task={}
            self.a = 100
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:sp1_3_bg_1",false,0,0,0,0,0,0,"mul+alpha",0.5,0.5,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["aya_bg_sp_4"]=Class(_spellcard_background)
_editor_class["aya_bg_sp_4"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:sp1_4_bg_2",true,0,0,0,0,-0.3,0,"mul+alpha",0.25, 0.25,
        function(self)
            self.task={}
            self.a = 100
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:sp1_4_bg_1",false,0,0,0,0,0,0,"mul+alpha",0.5,0.5,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
--------------------------------------------------------------------------------
--- 独立符卡名横幅（从 boss.sc_name 抽出，去掉 boss 依赖与历史记录）
--- 坐标系：世界坐标（与 boss.sc_name 一致，不调 SetViewMode）
---   → 作为普通 object 在 ObjRender 阶段渲染，用的就是 world 视图
---   → self.x/self.y 与 player.x/player.y 同一坐标系，可直接比较
--- 位置参考 boss 符卡名（终点 x=192、从右侧 +200 滑入），最终 y 默认更低
--- 保留原版“自机靠近淡出、离开恢复”机制
---
--- 用法：
---   Include('THlib/player/hifuu/merry/spellcard_name_banner.lua')
---   New(aya_sp_name_banner, "神奈川冲浪里")            -- 全默认，位置比 boss 符卡名低
---   New(aya_sp_name_banner, "神奈川冲浪里", 192, 150)  -- 指定终点 (192,150)
---
--- 复用的全局资源（THlib 已加载）：
---   贴图 boss_spell_name_bg（右对齐锚点 256×36）、TTF 字体 sc_name
--------------------------------------------------------------------------------

-- boss 符卡名横幅的基准（世界坐标，见 boss_ui.lua 的 sc_name）
local BOSS_SC_X       = 192  -- boss 符卡名终点 x（世界坐标，右边缘）
local BOSS_SC_Y       = 236  -- boss 符卡名终点 y
local BOSS_SC_XOFFSET = 200  -- 从右侧滑入的初始横向偏移
-- 本横幅最终 y 比 boss 符卡名低的量（世界坐标 y 向上，正数=更靠下）
local LOWER_BY        = 45

---@class aya_sp_name_banner
aya_sp_name_banner = Class(object)

--- 初始化（不传的参数一律回退到 boss 符卡名基准，最终 y 自动放低）
---@param text string       显示文本
---@param x1 number|nil      最终 x（默认 192，同 boss 符卡名）
---@param y1 number|nil      最终 y（默认 boss 符卡名 y - LOWER_BY）
---@param x0 number|nil      起始 x（默认 = 最终 x + 200，同 boss 从右滑入）
---@param y0 number|nil      起始 y（默认 = 最终 y）
---@param move_time number|nil  滑入用时（帧），默认 30
---@param hold_time number|nil  停留时长（帧）；nil = 常驻直到手动 Del
function aya_sp_name_banner:init(text, x1, y1, x0, y0, show_time, move_time, hold_time)
    self.layer = LAYER_TOP + 1
    self.group = GROUP_GHOST
    self.bound = false

    self.text = text or ""
    -- 最终位置：参考 boss 符卡名，y 默认放低
    self.x1 = x1 or BOSS_SC_X
    self.y1 = y1 or (BOSS_SC_Y - LOWER_BY)
    -- 起始位置：默认与 boss 一样从右侧滑入（终点 + 横向偏移），y 与终点同高
    self.x0 = x0 or (self.x1 + BOSS_SC_XOFFSET)
    self.y0 = y0 or self.y1
    self.show_time = show_time or 30
    self.move_time = move_time or 30
    self.hold_time = hold_time -- nil 则常驻

    self.x = self.x0
    self.y = self.y0
    self._alpha  = 0   -- 整体透明度 0-1
    self._scale  = 5   -- 文字初始放大（回弹到 1，制造“啪”地弹出感）
    self._scale2 = 1   -- 背景条附加缩放系数（1→0）
    self.flag    = 0   -- 自机靠近计数（0~18），越大越淡
end

function aya_sp_name_banner:frame()
	local st = self.show_time
    local mt = self.move_time
    local t  = self.timer

    if t <= st then
        -- 滑入 + 缩放回弹（sin 为角度制，sin(90*p) 实现缓出）
        local p = t / (st)
        local e = sin(90 * p)
        self._alpha  = p
        self._scale  = 1 + 4 * (1 - e) -- 5 → 1
        self._scale2 = 1 - e           -- 1 → 0
    elseif t <= mt + st then
    	local p = (t - st) / (mt)
        local e = sin(90 * p)
    	self.x = self.x0 + (self.x1 - self.x0) * e
        self.y = self.y0 + (self.y1 - self.y0) * e
    else
        self.x = self.x1
        self.y = self.y1
        self._alpha  = 1
        self._scale  = 1
        self._scale2 = 0
    end

    -- 自机靠近淡出、离开恢复（照抄 boss.sc_name 逻辑，世界坐标直接比较）
    -- flag 每帧 ±1，夹在 0~18；render 时 alpha 乘 (1 - flag/30)，最低约 0.4
    local near = false
    if t > mt and IsValid(player)
            and abs(player.x - self.x) <= 180
            and abs(player.y - self.y) <= 60 then
        near = true
    end
    if near then
        self.flag = self.flag + 1
    else
        self.flag = self.flag - 1
    end
    self.flag = min(max(0, self.flag), 18)

    -- 有停留时长则到点淡出并自删；否则常驻，需外部 Del
    if self.hold_time and t > mt + self.hold_time then
        self._alpha = self._alpha - 1 / 20
        if self._alpha <= 0 then
            Del(self)
        end
    end
end

function aya_sp_name_banner:render()
    -- 不调 SetViewMode：与 boss.sc_name 一致，用 ObjRender 阶段的世界视图

    -- 靠近淡出系数（1 = 正常，最低约 0.4）
    local near_fade = 1 - self.flag / 30
    local a = self._alpha * near_fade * 255

    -- 背景条（锚点右对齐 256 宽，故向 self.x 左侧延伸）
    SetImageState("boss_spell_name_bg", "", Color(a, 255, 255, 255))
    Render("boss_spell_name_bg", self.x, self.y, 0, 1 + 0.5 * self._scale2)

    -- 文字：先画 8 方向黑描边，再画白字（与原版一致）
    local ty = self.y - 10
    local s = GetImageScale()
    SetImageScale(s * self._scale)
    local d = sqrt(2)
    for i = 0, 8 do
        local _x = self.x + d * cos(i * 45)
        local _y = ty + d * sin(i * 45)
        RenderTTF("main_font_zh_cn", self.text,
                _x, _x, _y - 2, _y - 2,
                Color(a, 0, 0, 0),
                "right", "noclip")
    end
    RenderTTF("main_font_zh_cn", self.text,
            self.x, self.x, ty - 2, ty - 2,
            Color(a, 255, 255, 255),
            "right", "noclip")
    SetImageScale(s)
end

_editor_class["sc_1_p1_bu1"]=Class(bullet)
_editor_class["sc_1_p1_bu1"].init=function(self,_x,_y,angle,v)
bullet.init(self,water_drop_dark,COLOR_DEEP_BLUE,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,30,52,183)
    self.bound = false
    lasttask=task.New(self,function()
        do local a,_d_a=(angle),(0.6) for _=1,60 do
            SetV2(self,v,a,true,false)
            task._Wait(1)
        a=a+_d_a end end
        do local a,_d_a=(self._angle),(ran:Float(-0.8,-1.0)) for _=1,ran:Int(150, 180) do
            SetV2(self,v,a,true,false)
            task._Wait(1)
        a=a+_d_a end end
        self.bound = true
        local p = ran:Int(0,10)
        if p >=0 and p <= 1 then
            PlaySound("don00",0.1,self.x/256,false)
            last=New(_straight,ball_small,COLOR_GRAY,self.x,self.y,2,self._angle,false,0,false,true,0,false,0,0,0,false)
            _set_g(last,0.05)
            _forbid_v(last,'original','original',2)
            last.timer=11
            _del(self,true)
        elseif p <= 9 then
            _del(self,true)
        end
        _set_g(self,0.05)
        _forbid_v(self,'original','original',2)
        for _=1,_infinite do
            self.navi = true
            task._Wait(1)
        end
    end)
end
_editor_class["sc_1_p2_bu1"]=Class(bullet)
_editor_class["sc_1_p2_bu1"].init=function(self,_x,_y,_)
bullet.init(self,grain_a,COLOR_ORANGE,true,false)
self.x,self.y=_x,_y
    self.hide = true
    
    lasttask=task.New(self,function()
        lasttask=task.New(self,function()
            do local a,_d_a,t,_d_t=(ran:Float(-30, 30)),(6),(1),(1) for _=1,_infinite do
                local type = t % 13
                if type == 11 then
                    do
                        PlaySound("tan02",0.1,self.x/256,false)
                        last=New(_editor_class["sc_1_p2_bu4"],self.x + 40 * cos(a),self.y + 10 * sin(a),270 + 20 * cos(a), 2)
                        last=New(_editor_class["sc_1_p2_bu4"],self.x + 40 * cos(a + 120),self.y + 10 * sin(a + 120),270 + 20 * cos(a + 120), 2)
                        last=New(_editor_class["sc_1_p2_bu4"],self.x + 40 * cos(a + 240),self.y + 10 * sin(a + 240),270 + 20 * cos(a + 240), 2)
                        task._Wait(15)
                    end
                else
                    if type == 10 or type == 12 then
                        do
                            PlaySound("tan02",0.1,self.x/256,false)
                            last=New(_editor_class["sc_1_p2_bu3"],self.x + 40 * cos(a),self.y + 10 * sin(a),270 + 20 * cos(a), 2)
                            last=New(_editor_class["sc_1_p2_bu3"],self.x + 40 * cos(a + 120),self.y + 10 * sin(a + 120),270 + 20 * cos(a + 120), 2)
                            last=New(_editor_class["sc_1_p2_bu3"],self.x + 40 * cos(a + 240),self.y + 10 * sin(a + 240),270 + 20 * cos(a + 240), 2)
                            task._Wait(15)
                        end
                    else
                        do
                            PlaySound("tan00",0.1,self.x/256,false)
                            last=New(_editor_class["sc_1_p2_bu2"],self.x + 40 * cos(a),self.y + 10 * sin(a),270 + 20 * cos(a), 2)
                            last=New(_editor_class["sc_1_p2_bu2"],self.x + 40 * cos(a + 120),self.y + 10 * sin(a + 120),270 + 20 * cos(a + 120), 2)
                            last=New(_editor_class["sc_1_p2_bu2"],self.x + 40 * cos(a + 240),self.y + 10 * sin(a + 240),270 + 20 * cos(a + 240), 2)
                            task._Wait(10)
                        end
                    end
                end
            a=a+_d_a t=t+_d_t end end
        end)
        lasttask=task.New(self,function()
            task._Wait(60)
            task.MoveTo(-170, 224,180,MOVE_ACC_DEC)
            for _=1,_infinite do
                task.MoveTo(170, 224,360,MOVE_ACC_DEC)
                task.MoveTo(-170, 224,360,MOVE_ACC_DEC)
            end
        end)
    end)
end
_editor_class["sc_1_p2_bu2"]=Class(bullet)
_editor_class["sc_1_p2_bu2"].init=function(self,_x,_y,angle, v)
bullet.init(self,ball_mid,COLOR_ORANGE,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,255,255,255)
    SetV2(self,v,angle,true,false)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if self.y <= -224 then
                do break end
            else
            end
            task._Wait(1)
        end
        ChangeBulletImage(self,ball_mid,COLOR_GREEN)
        _object.set_color(self,"mul+add",255,255,255,255)
        self.rot = 180-self.rot
        self.vy = -self.vy
    end)
end
_editor_class["sc_1_p2_bu3"]=Class(bullet)
_editor_class["sc_1_p2_bu3"].init=function(self,_x,_y,angle, v)
bullet.init(self,ball_big,COLOR_ORANGE,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,255,255,255)
    SetV2(self,v,angle,true,false)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if self.y <= -224 then
                do break end
            else
            end
            task._Wait(1)
        end
        ChangeBulletImage(self,ball_big,COLOR_GREEN)
        _object.set_color(self,"mul+add",255,255,255,255)
        self.rot = 180-self.rot
        self.vy = -self.vy
    end)
end
_editor_class["sc_1_p2_bu4"]=Class(bullet)
_editor_class["sc_1_p2_bu4"].init=function(self,_x,_y,angle, v)
bullet.init(self,ball_huge,COLOR_ORANGE,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,255,255,255)
    SetV2(self,v,angle,true,false)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if self.y <= -224 then
                do break end
            else
            end
            task._Wait(1)
        end
        ChangeBulletImage(self,ball_huge,COLOR_GREEN)
        _object.set_color(self,"mul+add",255,255,255,255)
        self.rot = 180-self.rot
        self.vy = -self.vy
    end)
end
_editor_class["sc_1_p3_bu1"]=Class(bullet)
_editor_class["sc_1_p3_bu1"].init=function(self,_x,_y,angle,v)
bullet.init(self,arrow_big,COLOR_RED,true,false)
self.x,self.y=_x,_y
    self.hide = true
    self.colli = false
    lasttask=task.New(self,function()
        lasttask=task.New(self,function()
            local baseAngle = ran:Float(40, 60)
            -- 展开时的基础角度
            local baseAngleIval = 16
            -- 展开时的角度增量
            do local a,_d_a,t,_d_t=(angle),(-2),(baseAngle),(baseAngleIval) for _=1,30 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 5)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
            local x1 = self.x
            local y1 = self.y
            do local a,_d_a,t,_d_t=(self._angle),(4),(baseAngle),(baseAngleIval) for _=1,45 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 5)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
            local x2 = self.x
            local y2 = self.y
            
            local x_center = (x1 + x2) / 2
            local y_center = (y1 + y2) / 2
            local radius = sqrt((x2 - x1) * (x2 - x1)  + (y2 - y1) * (y2 - y1)) /2 - 15 - 10
            PlaySound("tan00",0.1,self.x/256,false)
            do local r,_d_r,nums,_d_nums=(radius),(-10),(60),(-8) for _=1,6 do
                local d = true
                do local a,_d_a=(ran:Float(0,360)),(360 / nums) for _=1,nums do
                    last=New(_editor_class["sc_1_p3_bu3"],x_center + r * cos(a), y_center + r * sin(a),1, a, 240 + 30 *  sin(6 * a), d, 1)
                    d = not d
                a=a+_d_a end end
            r=r+_d_r nums=nums+_d_nums end end
            x1 = self.x
            y1 = self.y
            do local a,_d_a,t,_d_t=(self._angle),(-4),(baseAngle),(baseAngleIval) for _=1,45 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 5)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
            x2 = self.x
            y2 = self.y
            x_center = (x1 + x2) / 2
            y_center = (y1 + y2) / 2
            radius = sqrt((x2 - x1) * (x2 - x1)  + (y2 - y1) * (y2 - y1)) /2 - 15 - 10
            do local r,_d_r,nums,_d_nums=(radius),(-10),(60),(-8) for _=1,6 do
                local d = true
                do local a,_d_a=(ran:Float(0,360)),(360 / nums) for _=1,nums do
                    last=New(_editor_class["sc_1_p3_bu3"],x_center + r * cos(a), y_center + r * sin(a),1, a, 240 + 30 *  sin(6 * a), d, 1)
                    d = not d
                a=a+_d_a end end
            r=r+_d_r nums=nums+_d_nums end end
            do local a,_d_a,t,_d_t=(self._angle),(2),(baseAngle),(baseAngleIval) for _=1,30 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 5)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 5)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
        end)
        lasttask=task.New(self,function()
        end)
    end)
end
_editor_class["sc_1_p3_bu1.5"]=Class(bullet)
_editor_class["sc_1_p3_bu1.5"].init=function(self,_x,_y,angle,v)
bullet.init(self,arrow_big,COLOR_RED,true,false)
self.x,self.y=_x,_y
    self.hide = true
    self.colli = false
    lasttask=task.New(self,function()
        lasttask=task.New(self,function()
            local baseAngle = ran:Float(-40, -60)
            -- 展开时的基础角度
            local baseAngleIval = -16
            -- 展开时的角度增量
            do local a,_d_a,t,_d_t=(angle),(2),(baseAngle),(baseAngleIval) for _=1,30 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 10)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
            local x1 = self.x
            local y1 = self.y
            do local a,_d_a,t,_d_t=(self._angle),(-4),(baseAngle),(baseAngleIval) for _=1,45 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 10)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
            local x2 = self.x
            local y2 = self.y
            
            local x_center = (x1 + x2) / 2
            local y_center = (y1 + y2) / 2
            local radius = sqrt((x2 - x1) * (x2 - x1)  + (y2 - y1) * (y2 - y1)) /2 - 15 - 10
            PlaySound("tan00",0.1,self.x/256,false)
            do local r,_d_r,nums,_d_nums=(radius),(-10),(60),(-8) for _=1,6 do
                local d = true
                do local a,_d_a=(ran:Float(0,360)),(360 / nums) for _=1,nums do
                    last=New(_editor_class["sc_1_p3_bu3"],x_center + r * cos(a), y_center + r * sin(a),1, a, 240 + 30 *  sin(6 * a), d, 12)
                    d = not d
                a=a+_d_a end end
            r=r+_d_r nums=nums+_d_nums end end
            x1 = self.x
            y1 = self.y
            do local a,_d_a,t,_d_t=(self._angle),(4),(baseAngle),(baseAngleIval) for _=1,45 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 10)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
            x2 = self.x
            y2 = self.y
            x_center = (x1 + x2) / 2
            y_center = (y1 + y2) / 2
            radius = sqrt((x2 - x1) * (x2 - x1)  + (y2 - y1) * (y2 - y1)) /2 - 15 - 10
            do local r,_d_r,nums,_d_nums=(radius),(-10),(60),(-8) for _=1,6 do
                local d = true
                do local a,_d_a=(ran:Float(0,360)),(360 / nums) for _=1,nums do
                    last=New(_editor_class["sc_1_p3_bu3"],x_center + r * cos(a), y_center + r * sin(a),1, a, 240 + 30 *  sin(6 * a), d, 12)
                    d = not d
                a=a+_d_a end end
            r=r+_d_r nums=nums+_d_nums end end
            do local a,_d_a,t,_d_t=(self._angle),(-2),(baseAngle),(baseAngleIval) for _=1,30 do
                do
                    SetV2(self,v,a,true,false)
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a + 90),self.y + 5 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 5 * cos(a - 90),self.y + 5 * sin(a - 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a + 90),self.y + 15 * sin(a + 90),2, t, 180, 10)
                    last=New(_editor_class["sc_1_p3_bu2"],self.x + 15 * cos(a - 90),self.y + 15 * sin(a - 90),2, t, 180, 10)
                    baseAngle = t
                    task._Wait(2)
                end
            a=a+_d_a t=t+_d_t end end
        end)
        lasttask=task.New(self,function()
        end)
    end)
end
_editor_class["sc_1_p3_bu2"]=Class(bullet)
_editor_class["sc_1_p3_bu2"].init=function(self,_x,_y,v,angle,t,color)
bullet.init(self,ball_small,COLOR_GRAY,true,false)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,255,255,255)
    lasttask=task.New(self,function()
        task._Wait(t)
        ChangeBulletImage(self,ball_mid,color)
        task._Wait(60)
        last=New(_straight,grain_a,color,self.x,self.y,1,angle - 30,false,0,true,true,0,false,0,0,0,false)
        _object.set_color(last,"mul+add",255,255,255,255)
        last=New(_straight,grain_a,color,self.x,self.y,1,angle + 30,false,0,true,true,0,false,0,0,0,false)
        _object.set_color(last,"mul+add",255,255,255,255)
        _del(self,true)
    end)
end
_editor_class["sc_1_p3_bu3"]=Class(bullet)
_editor_class["sc_1_p3_bu3"].init=function(self,_x,_y,v,angle,t,is_del,color)
bullet.init(self,ball_small,COLOR_GRAY,true,false)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,255,255,255)
    lasttask=task.New(self,function()
        task._Wait(t)
        ChangeBulletImage(self,grain_a,color)
        if is_del then
            _del(self,true)
        else
        end
        
        do local a,_d_a=(0),(v / 60) for _=1,60 do
            SetV2(self,a,angle,true,false)
            task._Wait(1)
        a=a+_d_a end end
    end)
end
_editor_class["sc_1_p4_la1"]=Class(laser)
_editor_class["sc_1_p4_la1"].init=function(self,_x,_y,angle)
    laser.init(self,COLOR_RED,_x,_y,0,1,500,1,8,5,10)
    laser.ChangeImage(self,4)
    self.bound=false
    self.is_contact=0
    lasttask=task.New(self,function()
        SetV2(self,0,angle,true,false)
        self.colli=false
        
        laser._TurnOn(self,10,true,true)
        self.colli=true
        for _=1,_infinite do
            local l1 = self.l1
            local l2 = self.l2
            local l3 = self.l3
            local angle1 = angle % 360
            local r1 = 80
            
            -- 激光方向向量
            local dir_x = cos(angle1)
            local dir_y = sin(angle1)
            
            -- 玩家相对发射源的向量
            local dx = player.x - self.x
            local dy = player.y - self.y
            local dist_player_sq = dx^2 + dy^2
            
            -- 射线方程：P = self + t * dir，求与玩家判定圆的交点
            -- |P - player|^2 = r1^2
            -- 展开成关于t的二次方程：at^2 + bt + c = 0
            local a = dir_x^2 + dir_y^2  -- 实际上 = 1
            local b = 2 * (self.x * dir_x - player.x * dir_x + self.y * dir_y - player.y * dir_y)
            local c = dist_player_sq - r1^2
            
            -- 判别式
            local discriminant = b^2 - 4*a*c
            
            if discriminant >= 0 and c < 0 then
                -- 有交点，且发射源在圆内或圆边缘（c<0表示发射源到玩家距离<r1，或者刚好等于）
                -- 取较小的t（最近的交点）
                local t = (-b - sqrt(discriminant)) / (2*a)
                
                if t > 0 then
                    -- 交点在激光前方
                    self.head_x = self.x + t * dir_x
                    self.head_y = self.y + t * dir_y
                    self.l2 = t - l1 - l3
                    self.is_contact = 1
                else
                    self.l2 = 500
                    self.is_contact = 0
                end
            elseif discriminant >= 0 then
                -- 有交点，发射源在圆外
                local t = (-b - sqrt(discriminant)) / (2*a)
                
                if t > 0 then
                    -- 检查玩家是否在激光圆柱体判定内
                    local proj = dx * dir_x + dy * dir_y  -- 玩家在激光方向上的投影
                    if proj > 0 then
                        local perp_dist_sq = dist_player_sq - proj^2  -- 垂直距离的平方
                        if perp_dist_sq <= r1^2 then
                            -- 在圆柱体内
                            self.head_x = self.x + t * dir_x
                            self.head_y = self.y + t * dir_y
                            self.l2 = t - l1 - l3
                            self.is_contact = 1
                        else
                            self.l2 = 500
                            self.is_contact = 0
                        end
                    else
                        self.l2 = 500
                        self.is_contact = 0
                    end
                else
                    self.l2 = 500
                    self.is_contact = 0
                end
            else
                -- 无交点
                self.l2 = 500
                self.is_contact = 0
            end
            
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _set_rel_pos(self,0,0,self.rot,false)
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        task._Wait(10)
        for _=1,_infinite do
            if self.is_contact==1 then
                PlaySound("tan02",0.1,self.x/256,false)
                last=New(_straight,arrow_big,COLOR_ORANGE,self.head_x,self.head_y,1,0,true,0,true,true,180,false,0,0,0,false)
                last=New(_straight,arrow_big,COLOR_RED,self.head_x,self.head_y,1.5,0,true,0,true,true,90,false,0,0,0,false)
            else
            end
            task._Wait(10)
        end
    end)
end
_editor_class["sc_1_p4_bu1"]=Class(bullet)
_editor_class["sc_1_p4_bu1"].init=function(self,_x,_y,v, angle)
bullet.init(self,arrow_big,COLOR_RED,false,false)
self.x,self.y=_x,_y
    self.hide = true
    self.colli = false
    self.bound = false
    SetV2(self,v,270,true,false)
    lasttask=task.New(self,function()
        last=New(_editor_class["sc_1_p4_la1"],self.x,self.y,angle)
        _connect(self,last,0,true)
        self.la = last
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if self.y <= -240 then
                if IsValid(self.la) then
                Del(self.la)
                end
                _del(self,true)
            else
            end
            task._Wait(1)
        end
    end)
end
_editor_class["sc_2_crow"]=Class(_object)
_editor_class["sc_2_crow"].init=function(self,_x,_y,angle, d, rot, type)
    self.x,self.y=_x,_y
    self.img="ani:crow"
    self.layer=LAYER_ENEMY
    self.group=GROUP_ENEMY
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=200
    self.maxhp=200
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.type = type
    self.bound = false
    self.hit = false
    lasttask=task.New(self,function()
        do local i,_d_i=(0),(255/50) for _=1,50 do
            _object.set_color(self,"mul+alpha",i,255,255,255)
            task._Wait(1)
        i=i+_d_i end end
    end)
    lasttask=task.New(self,function()
        do local r,_d_r,d1,_d_d1=(angle),(rot),(0),(d / 50) for _=1,_infinite do
            _set_rel_pos(self,min(d, d1) * cos(r), min(d, d1) * sin(r),self.rot,false)
            if self.hit then
                if IsValid(_boss) then
                _boss.crow_drank = self
                end
                PlaySound("ice",1.0,self.x/256,true)
                do break end
            else
            end
            task._Wait(1)
        r=r+_d_r d1=d1+_d_d1 end end
        _object.set_color(self,"mul+alpha",255,239,46,46)
        self.group = GROUP_INDES
        New(boss_cast_ef,self.x,self.y)
        task._Wait(60)
        PlaySound("old_power0",1.0,self.x/256,true)
        do
            task.MoveTo(-220,0,60,MOVE_ACCEL)
            task.MoveTo(220,ran:Float(100,140),60,MOVE_NORMAL)
            task.MoveTo(-220,ran:Float(100,140),30,MOVE_NORMAL)
            task.MoveTo(220,ran:Float(100,140),15,MOVE_NORMAL)
            task.MoveTo(-220,ran:Float(100,140),15,MOVE_NORMAL)
            self.colli = false
            for _=1,15 do
                last=New(_editor_class["sc_2_la"],-400, ran:Float(140, 100),30, ran:Float(-20, 20))
                task._Wait(10)
                last=New(_editor_class["sc_2_la"],400, ran:Float(140, 100),30, ran:Float(160, 200))
                task._Wait(10)
            end
            task._Wait(120)
            _del(self,true)
        end
    end)
end
_editor_class["sc_2_crow"].kill=function(self)
    self.class.base.kill(self)
    if self.type == 1 then
        do local a,_d_a=(ran:Float(0,360)),(36) for _=1,10 do
            last=New(_straight,ball_mid,COLOR_BLUE,self.x,self.y,2,a,false,0,true,true,0,false,0,0,0,false)
        a=a+_d_a end end
    else
        last=New(_straight,ball_mid,COLOR_YELLOW,self.x,self.y,3,0,true,0,true,true,0,false,0,0,0,false)
    end
end
_editor_class["sc_2_beer"]=Class(_object)
_editor_class["sc_2_beer"].init=function(self,_x,_y,angle, v)
    self.x,self.y=_x,_y
    self.img="ani:beer"
    self.layer=LAYER_PLAYER_BULLET+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=200
    self.maxhp=200
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.hscale = 0.75
    self.vscale = 0.75
    self.rot = 0
    lasttask=task.New(self,function()
        do local i,_d_i,a,_d_a=(0),(255/25),(0),(v/25) for _=1,25 do
            SetV2(self,a,angle,false,false)
            _object.set_color(self,"mul+alpha",i,255,255,255)
            task._Wait(1)
        i=i+_d_i a=a+_d_a end end
        local hit_time = 0
        local cd = 0
        self.first_hit = false
        for _=1,_infinite do
            if Dist(self, player) < 32 then
                if cd == 0 then
                    SetV2(self,v,Angle(player,self),false,false)
                    self.first_hit = true
                    cd = 10
                else
                end
            else
                cd = max(0, cd - 1)
            end
            for i, o in ObjList(GROUP_ENEMY) do
               if self.first_hit and lstg.ColliCheck(self, o) then
                    o.hit = true
                    Del(self)
               end
            end
            if self.y>224 then
                PlaySound("nice",1.0,self.x/256,true)
                self.y=448-self.y
                self.vy=-self.vy
                hit_time = hit_time + 1
                self.first_hit = true
            else
            end
            if self.y<-224 then
                PlaySound("nice",1.0,self.x/256,true)
                self.y=-448-self.y
                self.vy=-self.vy
                hit_time = hit_time + 1
                self.first_hit = true
            else
            end
            if self.x>196 then
                PlaySound("nice",1.0,self.x/256,true)
                self.x=392-self.x
                self.vx=-self.vx
                hit_time = hit_time + 1
                self.first_hit = true
            else
            end
            if self.x<-196 then
                PlaySound("nice",1.0,self.x/256,true)
                self.x=-392-self.x
                self.vx=-self.vx
                hit_time = hit_time + 1
                self.first_hit = true
            else
            end
            if hit_time == 9 then
                _object.set_color(self,"mul+alpha",255,255,74,0)
            else
            end
            if hit_time == 10 then
                do local a,_d_a=(ran:Float(0,360)),(18) for _=1,20 do
                    last=New(_straight,ball_big,COLOR_ORANGE,self.x,self.y,3,a,false,0,true,true,0,false,0,0,0,false)
                a=a+_d_a end end
                PlaySound("ice",1.0,self.x/256,true)
                _del(self,true)
            else
            end
            task._Wait(1)
        end
    end)
end
_editor_class["sc_2_la"]=Class(laser)
_editor_class["sc_2_la"].init=function(self,_x,_y,v, angle)
    laser.init(self,COLOR_RED,_x,_y,0,50,250,50,20,0,10)
    
    self.bound = false
    lasttask=task.New(self,function()
        laser._TurnOn(self,1,true,false)
        SetV2(self,v,angle,true,false)
        for _=1,60 do
            last=New(_straight,grain_a,COLOR_GREEN,self.x,self.y,3,ran:Float(80, 100),false,0,true,true,0,false,0,0,0,false)
            last.navi = true
            _set_g(last,0.03)
            _forbid_v(last,'original','original',3)
            task._Wait(1)
        end
        task._Wait(60)
        _del(self,true)
    end)
end
_editor_class["sc_3_photo"]=Class(_object)
_editor_class["sc_3_photo"].init=function(self,_x,_y,angle, t1, t2, t3,t4)
    self.x,self.y=_x,_y
    self.img="image:photo_dark"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_INDES
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    SetV2(self,0,angle,true,false)
    _object.set_color(self,"mul+alpha",0,255,255,255)
    self.hscale = 0
    self.vscale = 2
    self.a = 0.25
    self.b = 0.25
    self.colli = false
    lasttask=task.New(self,function()
        lstg.var.timeslow = 2
        PlaySound("ch00",1.0,self.x/256,true)
        do local a,_d_a,b,_d_b=(0),(150/t1),(0),(2 / t1) for _=1,t1 do
            _object.set_color(self,"mul+alpha",a,255,255,255)
            self.hscale = b
            self.vscale = 2
            task._Wait(1)
        a=a+_d_a b=b+_d_b end end
        if IsValid(_boss) then
        	_boss.photo = true
        end
        do local b,_d_b=(2),(-1.5/t2) for _=1,t2 do
            SetV2(self,2,0,true,true)
            self.hscale = b
            self.vscale = b
            task._Wait(1)
        b=b+_d_b end end
        SetV2(self,0,0,true,true)
        PlaySound("focusfix",1.0,self.x/256,true)
        task._Wait(t3)
        do local a,_d_a=(150),(-150/t4) for _=1,t4 do
            _object.set_color(self,"mul+alpha",a,255,255,255)
            task._Wait(1)
        a=a+_d_a end end
        if IsValid(_boss) then
        	_boss.photo = false
        end
        lstg.var.timeslow = nil
        _del(self,true)
    end)
end
_editor_class["sc_3_photo_light"]=Class(_object)
_editor_class["sc_3_photo_light"].init=function(self,_x,_y,angle, t1, t2, t3, t4)
    self.x,self.y=_x,_y
    self.img="image:photo_light"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_INDES
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    SetV2(self,0,angle,true,false)
    _object.set_color(self,"mul+alpha",0,255,255,255)
    self.hscale = 0
    self.vscale = 2
    self.a = 64
    self.b = 48
    self.colli = false
    lasttask=task.New(self,function()
        do local a,_d_a,b,_d_b=(0),(255/t1),(0),(2 / t1) for _=1,t1 do
            self.hscale = b
            self.vscale = 2
            task._Wait(1)
        a=a+_d_a b=b+_d_b end end
        do local b,_d_b=(2),(-1.5/t2) for _=1,t2 do
            SetV2(self,2,0,true,true)
            self.hscale = b
            self.vscale = b
            task._Wait(1)
        b=b+_d_b end end
        SetV2(self,0,0,true,true)
        do local a,_d_a=(0),(255/t3) for _=1,t3 do
            _object.set_color(self,"mul+alpha",a,255,255,255)
            task._Wait(1)
        a=a+_d_a end end
        self.colli = true
        do local a,_d_a,t,_d_t=(255),(-255/t4),(1),(1) for _=1,t4 do
            if t == 5 then
                self.colli = false
            else
            end
            _object.set_color(self,"mul+alpha",a,255,255,255)
            task._Wait(1)
        a=a+_d_a t=t+_d_t end end
        _del(self,true)
    end)
end
_editor_class["sc_3_bu_bird"]=Class(_object)
_editor_class["sc_3_bu_bird"].init=function(self,_x,_y,v, angle, r, g, b)
    self.x,self.y=_x,_y
    self.img="ani:bu_bird"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"mul+alpha",255,r,g,b)
    SetV2(self,0,angle,true,false)
    lasttask=task.New(self,function()
        do
            local _beg_v1=0 local v1=_beg_v1  local _w_v1=-90 local _end_v1=v local _d_w_v1=90/(30)
            for _=1,30 do
                SetV2(self,v1,angle,true,false)
                _w_v1=_w_v1+_d_w_v1 v1=(_end_v1-_beg_v1)*sin(_w_v1)+(_end_v1)
            end
        end
        task._Wait(1)
    end)
end
_editor_class["sc_3_bu_bird_2"]=Class(_object)
_editor_class["sc_3_bu_bird_2"].init=function(self,_x,_y,v, angle, r, g, b, rot)
    self.x,self.y=_x,_y
    self.img="ani:bu_bird"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"mul+alpha",255,r,g,b)
    SetV2(self,0,angle,true,false)
    lasttask=task.New(self,function()
        do
            local _beg_v1=0 local v1=_beg_v1  local _w_v1=-90 local _end_v1=v local _d_w_v1=90/(30)
            for _=1,30 do
                SetV2(self,v1,angle,true,false)
                task._Wait(1)
                _w_v1=_w_v1+_d_w_v1 v1=(_end_v1-_beg_v1)*sin(_w_v1)+(_end_v1)
            end
        end
    end)
    lasttask=task.New(self,function()
        do
            local _beg_a1=angle local a1=_beg_a1  local _w_a1=-90 local _end_a1=angle + rot * 180 local _d_w_a1=180/(180)
            for _=1,180 do
                SetV2(self,v,a1,true,false)
                task._Wait(1)
                _w_a1=_w_a1+_d_w_a1 a1=(_end_a1-_beg_a1)/2*sin(_w_a1)+((_end_a1+_beg_a1)/2)
            end
        end
    end)
end
_editor_class["sc_3_dark_fog"]=Class(_object)
_editor_class["sc_3_dark_fog"].init=function(self,_x,_y,v, angle,rot)
    self.x,self.y=_x,_y
    self.img="image:dark_fog"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_INDES
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"mul+alpha",0,255,255,255)
    SetV2(self,v,angle,true,false)
    self.hscale = 1.2
    self.vscale = 1.2
    lasttask=task.New(self,function()
        local a = 0
        for _=1,_infinite do
            if IsValid(_boss) then
                if _boss.photo then
                    a = max(a - 25.5, 0)
                    _object.set_color(self,"mul+alpha",a,255,255,255)
                else
                    a = min(a + 25.5, 255)
                    _object.set_color(self,"mul+alpha",a,255,255,255)
                end
            else
                _del(self,true)
            end
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        do
            local _beg_v1=0 local v1=_beg_v1  local _w_v1=-90 local _end_v1=v local _d_w_v1=90/(30)
            for _=1,30 do
                SetV2(self,v1,angle,true,false)
                task._Wait(1)
                _w_v1=_w_v1+_d_w_v1 v1=(_end_v1-_beg_v1)*sin(_w_v1)+(_end_v1)
            end
        end
    end)
    lasttask=task.New(self,function()
        do
            local _beg_a1=angle local a1=_beg_a1  local _w_a1=-90 local _end_a1=angle + rot * 180 local _d_w_a1=180/(180)
            for _=1,180 do
                SetV2(self,v,a1,true,false)
                task._Wait(1)
                _w_a1=_w_a1+_d_w_a1 a1=(_end_a1-_beg_a1)/2*sin(_w_a1)+((_end_a1+_beg_a1)/2)
            end
        end
    end)
end
_editor_class["sc4_laser"]=Class(laser)
_editor_class["sc4_laser"].init=function(self,_x,_y,rot)
    laser.init(self,COLOR_GRAY,_x,_y,0,0,250,100,8,0,0)
    
    self.rot=rot
    lasttask=task.New(self,function()
        laser._TurnOn(self,1,false,false)
        laser.grow(self,30,true,true)
    end)
end
_editor_class["sc5_slave"]=Class(enemy)
_editor_class["sc5_slave"].init=function(self,_x,_y,n,flag,N,list)
    enemy.init(self,24+flag,114514,false,false,false)
    self.x,self.y=_x,_y
    self.drop={0,0,0}
    task.New(self,function() self.protect=true task.Wait(1) self.protect=false end)
    self.r=20
    self.spell_immune=true
    _connect(_boss,self,1,true)
    lasttask=task.New(self,function()
        do local a,_d_a=(list[n]),(3) for _=1,_infinite do
            list[n]=360/N*n+a
            _set_rel_pos(self,self.r*cos(list[n]),self.r*sin(list[n]),self.rot,false)
            task._Wait(1)
        a=a+_d_a end end
    end)
    lasttask=task.New(self,function()
        do local a,_d_a=(5*n),(360/N) for _=1,_infinite do
            PlaySound("kira00",0.25,self.x/256,true)
            if flag==1 then
                last=New(_editor_class["sc5_grain1"],self.x+20*cos(list[n]),self.y+20*sin(list[n]),a)
            else
                last=New(_editor_class["sc5_square"],self.x+20*cos(list[n]),self.y+20*sin(list[n]),a)
            end
            task._Wait(10)
        a=a+_d_a end end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            PlaySound("kira00",0.25,self.x/256,true)
            last=New(_editor_class["sc5_grain2"],self.x,self.y,list[n]+90,flag)
            task._Wait(10)
        end
    end)
end
_editor_class["sc5_grain1"]=Class(bullet)
_editor_class["sc5_grain1"].init=function(self,_x,_y,a)
bullet.init(self,grain_a,COLOR_BLUE,true,true)
self.x,self.y=_x,_y
    lasttask=task.New(self,function()
        SetV2(self,3,a,true,false)
        task._Wait(10)
        SetV2(self,1,a,true,false)
        ChangeBulletImage(self,square,COLOR_BLUE)
        _object.set_color(self,"mul+add",200,255,255,255)
    end)
end
_editor_class["sc5_square"]=Class(bullet)
_editor_class["sc5_square"].init=function(self,_x,_y,a,co)
bullet.init(self,square,COLOR_GREEN,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",200,255,255,255)
    lasttask=task.New(self,function()
        SetV2(self,3,a,true,false)
        task._Wait(10)
        SetV2(self,1,a,true,false)
    end)
end
_editor_class["sc5_grain2"]=Class(bullet)
_editor_class["sc5_grain2"].init=function(self,_x,_y,a,sign)
bullet.init(self,grain_a,COLOR_CYAN,true,true)
self.x,self.y=_x,_y
    if sign==0 then
        ChangeBulletImage(self,grain_a,COLOR_GREEN)
        _object.set_color(self,"mul+add",200,255,255,255)
    else
    end
    lasttask=task.New(self,function()
        SetV2(self,0,a,true,false)
        task._Wait(120)
        SetV2(self,1,self.rot,true,false)
    end)
end
_editor_class["aya_bg_sp_0"]=Class(_spellcard_background)
_editor_class["aya_bg_sp_0"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:cdbg04b",true,0,0,0,-0.3,0.3,0,"mul+alpha",1,1,
        function(self)
            self.task={}
            self.a = 100
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:cdbg04a",false,0,0,0,0,0,0,"mul+alpha",1,1,
        function(self)
            self.task={}
            self.a = 200
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["Aya"]=Class(boss)
_editor_class["Aya"].cards={}
_editor_class["Aya"].name="Shameimaru Aya"
_editor_class["Aya"].bgm="bgm3"
_editor_class["Aya"]._bg=nil
_editor_class["Aya"].difficulty="All"
_editor_class["Aya"].init=function(self,cards)
boss.init(self,-150,160,_editor_class["Aya"].name,cards,New(_editor_class["aya_bg_sp_0"]),_editor_class["Aya"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("aya_walkImage.png",4,11,{4,7,7,11},{1,1,1},6,16,16)
    boss.SetUIDisplay(self,true,true,true,false,true,true)
end
_tmp_sc=boss.card.New("「通常攻击-1」",2,5,45,1200,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        do
            last=New(_editor_class["aya_charge"],self.x,self.y,'in', 60, 245, 220, 0)
            task._Wait(75)
            last=New(_editor_class["aya_charge"],self.x,self.y,'out', 30, 245, 220, 0)
        end
        for _=1,_infinite do
            do
                lasttask=task.New(self,function()
                    do local a,_d_a=(ran:Float(0,360)),(60) for _=1,12 do
                        PlaySound("tan02",0.1,self.x/256,false)
                        do local b,_d_b=(a),(36) for _=1,10 do
                            do local d,_d_d=(b),(24) for _=1,15 do
                                last=New(_straight,ball_mid_c,COLOR_RED,self.x + 20 * cos(d),self.y + 20 * sin(d),2.5,b,false,0,true,true,0,false,0,0,0,false)
                            d=d+_d_d end end
                        b=b+_d_b end end
                        task._Wait(30)
                    a=a+_d_a end end
                end)
                lasttask=task.New(self,function()
                    do local a,_d_a=(ran:Float(0,360)),(45) for _=1,6 do
                        PlaySound("tan01",0.1,self.x/256,false)
                        do local b,_d_b=(a),(60) for _=1,6 do
                            do local d,_d_d=(b),(36) for _=1,10 do
                                last=New(_straight,ball_mid_c,COLOR_BLUE,self.x + 60 * cos(d),self.y + 60 * sin(d),1.5,b,false,0,true,true,0,false,0,0,0,false)
                            d=d+_d_d end end
                        b=b+_d_b end end
                        task._Wait(60)
                    a=a+_d_a end end
                end)
            end
            task._Wait(360)
            task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_NORMAL,MOVE_X_TOWARDS_PLAYER)
            do
                lasttask=task.New(self,function()
                    do local a,_d_a=(ran:Float(0,360)),(-60) for _=1,12 do
                        PlaySound("tan02",0.1,self.x/256,false)
                        do local b,_d_b=(a),(36) for _=1,10 do
                            do local d,_d_d=(b),(24) for _=1,15 do
                                last=New(_straight,ball_mid_c,COLOR_DEEP_GREEN,self.x + 20 * cos(d),self.y + 20 * sin(d),2.5,b,false,0,true,true,0,false,0,0,0,false)
                            d=d+_d_d end end
                        b=b+_d_b end end
                        task._Wait(30)
                    a=a+_d_a end end
                end)
                lasttask=task.New(self,function()
                    do local a,_d_a=(ran:Float(0,360)),(-45) for _=1,6 do
                        PlaySound("tan01",0.1,self.x/256,false)
                        do local b,_d_b=(a),(60) for _=1,6 do
                            do local d,_d_d=(b),(36) for _=1,10 do
                                last=New(_straight,ball_mid_c,COLOR_CHARTREUSE,self.x + 60 * cos(d),self.y + 60 * sin(d),1.5,b,false,0,true,true,0,false,0,0,0,false)
                            d=d+_d_d end end
                        b=b+_d_b end end
                        task._Wait(60)
                    a=a+_d_a end end
                end)
            end
            task._Wait(360)
            task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_NORMAL,MOVE_X_TOWARDS_PLAYER)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","「通常攻击-1」",_tmp_sc,#_editor_class["Aya"].cards,false})
_tmp_sc=boss.card.New("旧约「以酒还酒」",2,5,90,800,{50,0,20},false)
function _tmp_sc:before()
    last=New(_editor_class["NB_Portrait_AI"],0,0,_)
    self.spellname=aic.ui.NewSpellname(self, '旧约「以酒还酒」')
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        for _=1,_infinite do
            New(boss_cast_ef, self.x, self.y, 250, 245, 220, 0, 30)
            local angle_beer = Angle(self, player)
            last=New(_editor_class["sc_2_beer"],self.x,self.y,angle_beer,2)
            self.beer = last
            self.crows = {}
            self.crow_drank = nil
            do local a,_d_a=(angle_beer - 22.5),(45) for _=1,8 do
                last=New(_editor_class["sc_2_crow"],self.x,self.y,a, 200, 0.5, 1)
                _connect(self,last,0,true)
                table.insert(self.crows, last)
            a=a+_d_a end end
            do local a,_d_a=(angle_beer - 30),(60) for _=1,6 do
                last=New(_editor_class["sc_2_crow"],self.x,self.y,a, 150, -0.4, 2)
                _connect(self,last,0,true)
                table.insert(self.crows, last)
            a=a+_d_a end end
            do local a,_d_a=(angle_beer - 60),(120) for _=1,3 do
                last=New(_editor_class["sc_2_crow"],self.x,self.y,a, 100, 0.3, 1)
                _connect(self,last,0,true)
                table.insert(self.crows, last)
            a=a+_d_a end end
            for _=1,_infinite do
                if self.hit == true then
                    PlaySound("enep00",0.5,self.x/256,true)
                    self.beer = nil
                    Damage(self, 450)
                    for i, o in ipairs(self.crows) do
                        if IsValid(o) then
                           Kill(o)
                        end
                    end
                    self.hit = false
                    self.crow_drank = nil
                    do break end
                else
                end
                if not IsValid(self.beer) then
                    self.beer = nil
                    if not IsValid(self.crow_drank) then
                        for i, o in ipairs(self.crows) do
                            if IsValid(o) then
                               Kill(o)
                            end
                        end
                        self.crow_drank = nil
                        do break end
                    else
                    end
                else
                end
                task._Wait(1)
            end
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
    if IsValid(self.spellname) then
        _del(self.spellname,true)
    else
    end
    for i, o in ipairs(self.crows) do
        if IsValid(o) then
            Del(o)
        end
    end
    
    if IsValid(self.beer) then
    	Del(self.beer)
    else
    	print("no beer")
    end
    
    if IsValid(self.crow_drank) then
    	Del(self.crow_drank)
    end
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","旧约「以酒还酒」",_tmp_sc,#_editor_class["Aya"].cards,false})
_tmp_sc=boss.card.New("「通常攻击-2」",2,5,45,1200,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        do
            last=New(_editor_class["aya_charge"],self.x,self.y,'in', 60, 245, 220, 0)
            task._Wait(75)
            last=New(_editor_class["aya_charge"],self.x,self.y,'out', 30, 245, 220, 0)
        end
        for _=1,_infinite do
            do
                lasttask=task.New(self,function()
                    do local a,_d_a=(-60),(18) for _=1,30 do
                        PlaySound("tan02",0.1,self.x/256,false)
                        do local d,_d_d=(a),(24) for _=1,15 do
                            last=New(_straight,ball_mid_c,COLOR_RED,self.x + 20 * cos(d),self.y + 20 * sin(d),2.5,a,false,0,true,true,0,true,0,0,0,false)
                        d=d+_d_d end end
                        task._Wait(10)
                    a=a+_d_a end end
                end)
                lasttask=task.New(self,function()
                    do local a,_d_a=(ran:Float(0,360)),(45) for _=1,6 do
                        PlaySound("tan01",0.1,self.x/256,false)
                        do local b,_d_b=(a),(60) for _=1,6 do
                            do local d,_d_d=(b),(36) for _=1,10 do
                                last=New(_straight,ball_mid_c,COLOR_BLUE,self.x + 60 * cos(d),self.y + 60 * sin(d),1.5,b,false,0,true,true,0,false,0,0,0,false)
                            d=d+_d_d end end
                        b=b+_d_b end end
                        task._Wait(60)
                    a=a+_d_a end end
                end)
            end
            task._Wait(360)
            task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_NORMAL,MOVE_X_TOWARDS_PLAYER)
            do
                lasttask=task.New(self,function()
                    do local a,_d_a=(240),(-18) for _=1,30 do
                        PlaySound("tan02",0.1,self.x/256,false)
                        do local d,_d_d=(a),(24) for _=1,15 do
                            last=New(_straight,ball_mid_c,COLOR_DEEP_GREEN,self.x + 20 * cos(d),self.y + 20 * sin(d),2.5,a,false,0,true,true,0,true,0,0,0,false)
                        d=d+_d_d end end
                        task._Wait(10)
                    a=a+_d_a end end
                end)
                lasttask=task.New(self,function()
                    do local a,_d_a=(ran:Float(0,360)),(-45) for _=1,6 do
                        PlaySound("tan01",0.1,self.x/256,false)
                        do local b,_d_b=(a),(60) for _=1,6 do
                            do local d,_d_d=(b),(36) for _=1,10 do
                                last=New(_straight,ball_mid_c,COLOR_CHARTREUSE,self.x + 60 * cos(d),self.y + 60 * sin(d),1.5,b,false,0,true,true,0,false,0,0,0,false)
                            d=d+_d_d end end
                        b=b+_d_b end end
                        task._Wait(60)
                    a=a+_d_a end end
                end)
            end
            task._Wait(360)
            task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_NORMAL,MOVE_X_TOWARDS_PLAYER)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","「通常攻击-2」",_tmp_sc,#_editor_class["Aya"].cards,false})
table.insert(_editor_class["Aya"].cards,boss.move.New(0,120,60,MOVE_ACC_DEC))
_tmp_sc=boss.card.New("广重「卯酉之道，心之旅」",93,93,93,1800,{0,0,0},false)
function _tmp_sc:before()
    last=New(_editor_class["NB_Portrait_AI"],0,0,_)
    self.spellname=aic.ui.NewSpellname(self, '广重「卯酉之道，心之旅」')
end
function _tmp_sc:init()
    AddSPPoint(9999,1019,nil)
    AddSPPoint(9999,2579,nil)
    AddSPPoint(9999,4079,nil)
    lasttask=task.New(self,function()
        _boss.bound = false
        boss.show_aura(self,false)
        boss.SetUIDisplay(self,true,true,true,false,true,false)
        task.MoveTo(0,260,60,MOVE_ACC_DEC)
        do
            PlaySound("heal",1.0,self.x/256,true)
            if IsValid(_boss.bg) then Del(_boss.bg) end
                _boss.bg = New(_editor_class["aya_bg_sp_1"])
            local banner = aic.ui.NewSpellname(self, "「始发·15s的蓝色大海」", 1, 0, -45)
            banner.no_info=true
            misc.ShakeScreen(60,3)
            New(boss_cast_ef, 192, -170, 250, 100, 150, 255, 45)
            task._Wait(60)
            for _=1,90 do
                for _=1,30 do
                    last=New(_editor_class["sc_1_p1_bu1"],ran:Float(210,220),ran:Float(-120,-240),ran:Float(160,170), ran:Float(2.8,3))
                end
                PlaySound("tan02",0.1,self.x/256,false)
                task._Wait(10)
            end
            _clear_bullet(false,false)
            _del(banner,true)
        end
        do
            PlaySound("heal",1.0,self.x/256,true)
            if IsValid(_boss.bg) then Del(_boss.bg) end
                _boss.bg = New(_editor_class["aya_bg_sp_2"])
            local banner = aic.ui.NewSpellname(self, "「地下段·青木原传说」", 1, 0, -45)
            banner.no_info=true
            misc.ShakeScreen(60,3)
            New(boss_cast_ef, 0, 224, 250, 0, 230, 0, 45)
            task._Wait(60)
            last=New(_editor_class["sc_1_p2_bu1"],0, 224,_)
            task._Wait(1500)
            _clear_bullet(false,true)
            _del(banner,true)
        end
        do
            PlaySound("heal",1.0,self.x/256,true)
            if IsValid(_boss.bg) then Del(_boss.bg) end
                _boss.bg = New(_editor_class["aya_bg_sp_3"])
            local banner = aic.ui.NewSpellname(self, "「经停·富士枯山水」", 1, 0, -45)
            banner.no_info=true
            misc.ShakeScreen(60,3)
            task._Wait(120)
            last=New(_editor_class["sc_1_p3_bu1"],-192,224,-45, 3)
            task._Wait(540)
            last=New(_editor_class["sc_1_p3_bu1.5"],192,224,-135, 3)
            task._Wait(840)
            _clear_bullet(false,true)
            _del(banner,true)
        end
        do
            PlaySound("heal",1.0,self.x/256,true)
            if IsValid(_boss.bg) then Del(_boss.bg) end
                _boss.bg = New(_editor_class["aya_bg_sp_4"])
            banner = aic.ui.NewSpellname(self, "「终点·千本鸟居之京城」", 1, 0, -45)
            banner.no_info=true
            misc.ShakeScreen(60,3)
            task._Wait(120)
            do local t,_d_t=(60),(-2) for _=1,40 do
                last=New(_editor_class["sc_1_p4_bu1"],-200, 230,3,0)
                last=New(_editor_class["sc_1_p4_bu1"],200, 230,3,180)
                task._Wait(max(t, 20))
            t=t+_d_t end end
            task._Wait(180)
            _del(banner,true)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
    if IsValid(self.spellname) then
        _del(self.spellname,true)
    else
    end
end
function _tmp_sc:after()
    if IsValid(_boss.bg) then Del(_boss.bg) end
        _boss.bg = New(_editor_class["aya_bg_sp_0"])
    boss.SetUIDisplay(self,true,true,true,false,true,true)
    boss.show_aura(self,true)
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","广重「卯酉之道，心之旅」",_tmp_sc,#_editor_class["Aya"].cards,false})
table.insert(_editor_class["Aya"].cards,boss.move.New(0,120,60,MOVE_ACC_DEC))
_tmp_sc=boss.card.New("鸟船「奇美拉摄影展」",2,5,90,1600,{0,0,0},false)
function _tmp_sc:before()
    last=New(_editor_class["NB_Portrait_AI"],0,0,_)
    self.spellname=aic.ui.NewSpellname(self, '鸟船「奇美拉摄影展」')
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        lasttask=task.New(self,function()
            task._Wait(120)
            for _=1,_infinite do
                do local a,_d_a=(ran:Float(0,360)),(12) for _=1,30 do
                    last=New(_editor_class["sc_3_dark_fog"],self.x,self.y,1,a, 0.3)
                a=a+_d_a end end
                do local a,_d_a=(ran:Float(0,360)),(9) for _=1,40 do
                    last=New(_editor_class["sc_3_bu_bird_2"],self.x,self.y,1, a, 255, 255, 255, 0.3)
                    last=New(_editor_class["sc_3_bu_bird_2"],self.x,self.y,1, a, 255, 255, 255, -0.3)
                a=a+_d_a end end
                PlaySound("tan01",0.1,self.x/256,false)
                local a1 = Angle(self, player)
                local d = 0
                local dp = Dist(self, player)
                if dp > 150 then
                	d = dp - 150
                end
                task._Wait(240)
                last=New(_editor_class["sc_3_photo"],self.x + d * cos(a1), self.y + d * sin(a1),Angle(self,player), 10, 60, 5, 15)
                last=New(_editor_class["sc_3_photo_light"],self.x + d * cos(a1), self.y + d * sin(a1),Angle(self,player), 10, 60, 5, 15)
            end
        end)
        lasttask=task.New(self,function()
            do local i,_d_i=(ran:Float(0, 360)),(17) for _=1,_infinite do
                do local a,_d_a=(i),(15) for _=1,30 do
                    do local b,_d_b=(a),(120) for _=1,3 do
                        last=New(_editor_class["sc_3_bu_bird"],self.x + 10 * cos(b),self.y + 10 * sin(b),2, b, 180, 180, 0)
                    b=b+_d_b end end
                    PlaySound("tan00",0.1,self.x/256,false)
                    task._Wait(10)
                a=a+_d_a end end
                do local a,_d_a=(i),(-15) for _=1,30 do
                    do local b,_d_b=(a),(120) for _=1,3 do
                        last=New(_editor_class["sc_3_bu_bird"],self.x + 10 * cos(b),self.y + 10 * sin(b),2, b, 180, 180, 0)
                    b=b+_d_b end end
                    PlaySound("tan00",0.1,self.x/256,false)
                    task._Wait(10)
                a=a+_d_a end end
            i=i+_d_i end end
        end)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                do local a,_d_a=(ran:Float(0,360)),(18) for _=1,20 do
                    last=New(_editor_class["sc_3_bu_bird"],self.x + 10 * cos(a),self.y + 10 * sin(a),3, a, 0, 255, 150)
                a=a+_d_a end end
                PlaySound("tan00",0.1,self.x/256,false)
                task._Wait(10)
                do local a,_d_a=(ran:Float(0,360)),(18) for _=1,20 do
                    last=New(_editor_class["sc_3_bu_bird"],self.x + 10 * cos(a),self.y + 10 * sin(a),3, a, 0, 255, 150)
                a=a+_d_a end end
                PlaySound("tan00",0.1,self.x/256,false)
                task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_ACC_DEC,MOVE_X_TOWARDS_PLAYER)
                task._Wait(60)
            end
        end)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
    lstg.var.timeslow = nil
    if IsValid(self.spellname) then
        _del(self.spellname,true)
    else
    end
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","鸟船「奇美拉摄影展」",_tmp_sc,#_editor_class["Aya"].cards,false})
table.insert(_editor_class["Aya"].cards,boss.move.New(0,120,60,MOVE_ACC_DEC))
_tmp_sc=boss.card.New("莲台野「墓碑后的冥界」",2,5,60,400,{0,0,0},false)
function _tmp_sc:before()
    last=New(_editor_class["NB_Portrait_AI"],0,0,_)
    self.spellname=aic.ui.NewSpellname(self, '莲台野「墓碑后的冥界」')
end
function _tmp_sc:init()
    self.group=GROUP_NONTJT
    lasttask=task.New(self,function()
        task.MoveTo(0, 0,60,MOVE_ACC_DEC)
        New(boss_cast_ef,0, 0, nil, 255, 255, 255)
        last=New(_straight,square,COLOR_GRAY,0, 0,0,90,false,0,true,false,0,false,0,0,0,false)
        local s=(5)
        last.a=last.a+3
        last.b=last.b+3
        last.hscale = s
        last.vscale = 0
        last.a = last.a * s
        last._b = last.b
        last.b = 0
        last.timer = 11
        PlaySound("boon01",0.5,self.x/256,true)
        lasttask=task.New(last,function()
            local self=task.GetSelf()
            do
                local _beg_v=0 local v=_beg_v local _end_v=s local _w_v=0  local _d_w_v=1/(60-1)
                for _=1,60 do
                    self.vscale = v
                    self.b = self._b * v
                    task._Wait(1)
                    _w_v=_w_v+_d_w_v v=(_end_v-_beg_v)*_w_v^2+_beg_v
                end
            end
            local master=(self)
            last=New(_editor_class["sc4_laser"],self.x - self.a, self.y + self.b,180)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            last=New(_editor_class["sc4_laser"],self.x + self.a, self.y + self.b,90)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            last=New(_editor_class["sc4_laser"],self.x - self.a, self.y - self.b,-90)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            last=New(_editor_class["sc4_laser"],self.x + self.a, self.y - self.b,0)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            task._Wait(60)
            for _=1,_infinite do
                local rot0=(self.rot)
                do
                    local _beg_rot=rot0 local rot=_beg_rot local _end_rot=rot0 + 90 local _w_rot=0 local _d_w_rot=1/(120-1)
                    for _=1,120 do
                        self.rot=rot
                        task._Wait(1)
                        _w_rot=_w_rot+_d_w_rot if _w_rot<0.5 then rot=2*(_end_rot-_beg_rot)*_w_rot^2+_beg_rot else rot=(_end_rot-_beg_rot)*(-2*_w_rot^2+4*_w_rot-1)+_beg_rot end
                    end
                end
                task._Wait(60)
                PlaySound("kira00",0.5,self.x/256,true)
                local a0=(Angle(self,player))
                do
                    local _beg_a=a0 local a=_beg_a local _end_a=a0+360 local _d_a=(_end_a-_beg_a)/(90)
                    local _h_r=(60-(30))/2 local _t_r=(60+(30))/2 local r=_h_r*sin(-180)+_t_r local _w_r=-180 local _d_w_r=6*360/(90)
                    for _=1,90 do
                        last=New(_straight,grain_a,COLOR_PURPLE,self.x + r * cos(a), self.y + r * sin(a),1.5,a,false,0,true,true,0,false,0,0,0,false)
                        lasttask=task.New(last,function()
                            local self=task.GetSelf()
                            for _=1,12 do
                                if ran:Int(1,100)>=95 then
                                    last=New(_straight,ball_mid,COLOR_PURPLE,self.x,self.y,0.5,ran:Float(0, 360),false,0,true,true,0,false,0,0,0,false)
                                    lasttask=task.New(last,function()
                                        local self=task.GetSelf()
                                        task._Wait(300)
                                        _del(self,true)
                                    end)
                                end
                                task._Wait(5)
                            end
                        end)
                        a=a+_d_a
                        _w_r=_w_r+_d_w_r r=_h_r*sin(_w_r)+_t_r
                    end
                end
                do
                    local _beg_a=a0 local a=_beg_a local _end_a=a0+360 local _d_a=(_end_a-_beg_a)/(90)
                    local _h_r=(90-(30))/2 local _t_r=(90+(30))/2 local r=_h_r*sin(0)+_t_r local _w_r=0 local _d_w_r=6*360/(90)
                    for _=1,90 do
                        last=New(_straight,grain_a,COLOR_PURPLE,self.x + r * cos(a), self.y + r * sin(a),1.5,a,false,0,true,true,0,false,0,0,0,false)
                        lasttask=task.New(last,function()
                            local self=task.GetSelf()
                            for _=1,12 do
                                if ran:Int(1,100)>=95 then
                                    last=New(_straight,ball_mid,COLOR_PURPLE,self.x,self.y,0.5,ran:Float(0, 360),false,0,true,true,0,false,0,0,0,false)
                                    lasttask=task.New(last,function()
                                        local self=task.GetSelf()
                                        task._Wait(300)
                                        _del(self,true)
                                    end)
                                end
                                task._Wait(5)
                            end
                        end)
                        a=a+_d_a
                        _w_r=_w_r+_d_w_r r=_h_r*sin(_w_r)+_t_r
                    end
                end
                task._Wait(180)
            end
        end)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
    self.group=GROUP_ENEMY
    if IsValid(self.spellname) then
        _del(self.spellname,true)
    else
    end
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","莲台野「墓碑后的冥界」",_tmp_sc,#_editor_class["Aya"].cards,false})
table.insert(_editor_class["Aya"].cards,boss.move.New(0,120,60,MOVE_ACC_DEC))
_tmp_sc=boss.card.New("伊奘诺「神秘的具象」",50,50,50,1800,{0,0,0},false)
function _tmp_sc:before()
    last=New(_editor_class["NB_Portrait_AI"],0,0,_)
    self.spellname=aic.ui.NewSpellname(self, '伊奘诺「神秘的具象」')
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        --[[ 这个弹设是两三年前的，所以写得非常烂，但莫名奇妙地产生了一种周期性变化，所以就不过多改动了
        ]]
        task.MoveTo(0,0,60,MOVE_ACC_DEC)
        local N=(10)
        local list=({})
        for i=1,N do
            list[i]=0
        end
        do local sign,_d_sign=(1),(1) for _=1,12 do
            do local n,_d_n=(1),(1) for _=1,N do
                last=New(_editor_class["sc5_slave"],self.x,self.y,n,sign%2,N,list)
            n=n+_d_n end end
            for _,unit in ObjList(GROUP_ENEMY) do
                lasttask=task.New(unit,function()
                    local self=task.GetSelf()
                    do
                        local _beg_r=20 local r=_beg_r local _end_r=120 local _d_r=(_end_r-_beg_r)/(120-1)
                        for _=1,120 do
                            self.r=r
                            task._Wait(1)
                            r=r+_d_r
                        end
                    end
                end)
            end
            task._Wait(120)
            for _,unit in ObjList(GROUP_ENEMY) do
                lasttask=task.New(unit,function()
                    local self=task.GetSelf()
                    do
                        local _beg_r=120 local r=_beg_r local _end_r=20 local _d_r=(_end_r-_beg_r)/(120-1)
                        for _=1,120 do
                            self.r=r
                            task._Wait(1)
                            r=r+_d_r
                        end
                    end
                end)
            end
            task._Wait(120)
            self.group=GROUP_GHOST
            for _,unit in ObjList(GROUP_ENEMY) do
                _kill(unit,true)
            end
            self.group=GROUP_ENEMY
        sign=sign+_d_sign end end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
    if IsValid(self.spellname) then
        _del(self.spellname,true)
    else
    end
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","伊奘诺「神秘的具象」",_tmp_sc,#_editor_class["Aya"].cards,false})
_tmp_sc=boss.card.New("「通常攻击-显示对话用」",5,5,5,1800,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    _kill(self,true)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","「通常攻击-显示对话用」",_tmp_sc,#_editor_class["Aya"].cards,false})
stage.group.New('menu',{},"Hard",{lifeleft=7,power=400,faith=50000,bomb=3},true,1)
stage.group.AddStage('Hard','SpellCard@Hard',{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('SpellCard@Hard','init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(HM_hzc4_background)
        task._Wait(60)
        LoadMusicRecord("bgm2")
        _play_music("bgm2")
        local _boss_wait=true
        local _ref=New(_editor_class["Aya"],_editor_class["Aya"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
