-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
Include'AiC_forest.lua'
_editor_class["全黑背景过渡"]=Class(_object)
_editor_class["全黑背景过渡"].init=function(self,_x,_y,_)
    self.x,self.y=_x,_y
    self.img="image:全黑背景"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do local a,_d_a=(0),(255/120) for _=1,120 do
            _object.set_color(self,"",a,0,0,0)
            task._Wait(1)
        a=a+_d_a end end
        do local a,_d_a=(255),(-255/120) for _=1,120 do
            _object.set_color(self,"",a,0,0,0)
            task._Wait(1)
        a=a+_d_a end end
    end)
end
_editor_class["Boss"]=Class(boss)
_editor_class["Boss"].cards={}
_editor_class["Boss"].name="Name"
_editor_class["Boss"].bgm=""
_editor_class["Boss"]._bg=nil
_editor_class["Boss"].difficulty="All"
_editor_class["Boss"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Boss"].name,cards,New(spellcard_background),_editor_class["Boss"].difficulty)
end
stage.group.New('menu',{},"SpellCard",{lifeleft=7,power=400,faith=50000,bomb=3},true,1)
stage.group.AddStage('SpellCard','SpellCard@SpellCard',{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('SpellCard@SpellCard','init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(magic_forest_background)
        --[[ 红魔馆内部
        ]]
        --[[ 神社前院上空
        ]]
        --[[ 银河系
        ]]
        --[[ 绀珠传4面（冰冻的月之都）
        ]]
        --[[ 绀珠传6面（月海）
        ]]
        --[[ 地灵殿3面（旧地狱街道）
        ]]
        --[[ 地灵殿4面（地灵殿）
        ]]
        --[[ 不知道什么玩意
        ]]
        --[[ 天空璋3面（樱海）
        ]]
        --[[ 守矢神社（默认）
        ]]
        --[[ 博丽神社
        ]]
        --[[ 魔法森林
        ]]
        --[[ 魔法森林（快速）
        ]]
        --[[ 大结界上空
        ]]
        --[[ 一堆正方体
        ]]
        --[[ 红魔馆走廊
        ]]
        --[[ 冻结的雾之湖
        ]]
        --[[ 辉针城1面（雾之湖）
        ]]
        --[[ 连缘灵烈传5面（红色网格）
        ]]
        --[[ 风神录3面（妖怪之山外溪流）
        ]]
        --[[ 星空（类似神灵庙6面）
        ]]
        --[[ 森林（不知道在哪）
        ]]
        New(world_background)
        --[[ 蓝色网格
        ]]
        --[[ 永夜抄4面（迷途竹林）
        ]]
        task._Wait(60)
        LoadMusicRecord("spellcard")
        _play_music("spellcard")
        local _boss_wait=true
        local _ref=New(_editor_class["Boss"],_editor_class["Boss"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
