-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
_editor_class["Boss"]=Class(boss)
_editor_class["Boss"].cards={}
_editor_class["Boss"].name="Name"
_editor_class["Boss"].bgm=""
_editor_class["Boss"]._bg=nil
_editor_class["Boss"].difficulty="All"
_editor_class["Boss"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Boss"].name,cards,New(spellcard_background),_editor_class["Boss"].difficulty)
end
_tmp_sc=boss.card.New("",2,5,60,1800,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        local a=(50)
        do local th,_d_th=(0),(1) for _=1,_infinite do
            last=New(_straight,ball_small,COLOR_RED,self.x+a*cos(5*th),self.y+b*sin(7*th-90),0,Angle(self.x,self.y,self.x+a*cos(th),self.y+b*sin(3*th+60)),false,0,true,true,0,false,0,0,0,false)
            task._Wait(1)
        th=th+_d_th end end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Boss"].cards,_tmp_sc)

stage.group.New('menu',{},"Normal",{lifeleft=7,power=400,faith=50000,bomb=3},true,1)
stage.group.AddStage('Normal','SpellCard@Normal',{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('SpellCard@Normal','init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(woods_background)
        task._Wait(60)
        task._Wait(18000)
        LoadMusicRecord("spellcard")
        _play_music("spellcard")
        task._Wait(18000)
    end)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
