-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
_editor_class["sc4_laser"]=Class(laser)
_editor_class["sc4_laser"].init=function(self,_x,_y,rot)
    laser.init(self,COLOR_GRAY,_x,_y,0,0,250,100,8,0,0)
    
    self.rot=rot
    lasttask=task.New(self,function()
        laser._TurnOn(self,1,false,false)
        laser.grow(self,30,true,true)
    end)
end
_editor_class["sc5_slave"]=Class(enemy)
_editor_class["sc5_slave"].init=function(self,_x,_y,n,flag,N,list)
    enemy.init(self,24+flag,114514,false,false,false)
    self.x,self.y=_x,_y
    self.drop={0,0,0}
    task.New(self,function() self.protect=true task.Wait(1) self.protect=false end)
    self.r=20
    self.spell_immune=true
    _connect(_boss,self,1,true)
    lasttask=task.New(self,function()
        do local a,_d_a=(list[n]),(3) for _=1,_infinite do
            list[n]=360/N*n+a
            _set_rel_pos(self,self.r*cos(list[n]),self.r*sin(list[n]),self.rot,false)
            task._Wait(1)
        a=a+_d_a end end
    end)
    lasttask=task.New(self,function()
        do local a,_d_a=(5*n),(360/N) for _=1,_infinite do
            PlaySound("kira00",0.25,self.x/256,true)
            if flag==1 then
                last=New(_editor_class["sc5_grain1"],self.x+20*cos(list[n]),self.y+20*sin(list[n]),a)
            else
                last=New(_editor_class["sc5_square"],self.x+20*cos(list[n]),self.y+20*sin(list[n]),a)
            end
            task._Wait(10)
        a=a+_d_a end end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            PlaySound("kira00",0.25,self.x/256,true)
            last=New(_editor_class["sc5_grain2"],self.x,self.y,list[n]+90,flag)
            task._Wait(10)
        end
    end)
end
_editor_class["sc5_grain1"]=Class(bullet)
_editor_class["sc5_grain1"].init=function(self,_x,_y,a)
bullet.init(self,grain_a,COLOR_BLUE,true,true)
self.x,self.y=_x,_y
    lasttask=task.New(self,function()
        SetV2(self,3,a,true,false)
        task._Wait(10)
        SetV2(self,1,a,true,false)
        ChangeBulletImage(self,square,COLOR_BLUE)
        _object.set_color(self,"mul+add",200,255,255,255)
    end)
end
_editor_class["sc5_square"]=Class(bullet)
_editor_class["sc5_square"].init=function(self,_x,_y,a,co)
bullet.init(self,square,COLOR_GREEN,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",200,255,255,255)
    lasttask=task.New(self,function()
        SetV2(self,3,a,true,false)
        task._Wait(10)
        SetV2(self,1,a,true,false)
    end)
end
_editor_class["sc5_grain2"]=Class(bullet)
_editor_class["sc5_grain2"].init=function(self,_x,_y,a,sign)
bullet.init(self,grain_a,COLOR_CYAN,true,true)
self.x,self.y=_x,_y
    if sign==0 then
        ChangeBulletImage(self,grain_a,COLOR_GREEN)
        _object.set_color(self,"mul+add",200,255,255,255)
    else
    end
    lasttask=task.New(self,function()
        SetV2(self,0,a,true,false)
        task._Wait(120)
        SetV2(self,1,self.rot,true,false)
    end)
end
_editor_class["Aya"]=Class(boss)
_editor_class["Aya"].cards={}
_editor_class["Aya"].name="Shameimaru Aya"
_editor_class["Aya"].bgm=""
_editor_class["Aya"]._bg=nil
_editor_class["Aya"].difficulty="All"
_editor_class["Aya"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Aya"].name,cards,New(spellcard_background),_editor_class["Aya"].difficulty)
end
_tmp_sc=boss.card.New("莲台野「墓碑后的冥界」",2,5,60,400,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    self.group=GROUP_NONTJT
    lasttask=task.New(self,function()
        task.MoveTo(0, 0,60,MOVE_ACC_DEC)
        New(boss_cast_ef,0, 0, nil, 255, 255, 255)
        last=New(_straight,square,COLOR_GRAY,0, 0,0,90,false,0,true,false,0,false,0,0,0,false)
        local s=(5)
        last.a=last.a+3
        last.b=last.b+3
        last.hscale = s
        last.vscale = 0
        last.a = last.a * s
        last._b = last.b
        last.b = 0
        last.timer = 11
        PlaySound("boon01",0.5,self.x/256,true)
        lasttask=task.New(last,function()
            local self=task.GetSelf()
            do
                local _beg_v=0 local v=_beg_v local _end_v=s local _w_v=0  local _d_w_v=1/(60-1)
                for _=1,60 do
                    self.vscale = v
                    self.b = self._b * v
                    task._Wait(1)
                    _w_v=_w_v+_d_w_v v=(_end_v-_beg_v)*_w_v^2+_beg_v
                end
            end
            local master=(self)
            last=New(_editor_class["sc4_laser"],self.x - self.a, self.y + self.b,180)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            last=New(_editor_class["sc4_laser"],self.x + self.a, self.y + self.b,90)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            last=New(_editor_class["sc4_laser"],self.x - self.a, self.y - self.b,-90)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            last=New(_editor_class["sc4_laser"],self.x + self.a, self.y - self.b,0)
            lasttask=task.New(last,function()
                local self=task.GetSelf()
                _connect(master,self,0,true)
                local a=(Angle(self, master))
                local r=(Dist(self, master))
                local base_rot=(self.rot)
                local last_rot=(master.rot)
                for _=1,_infinite do
                    local d = master.rot - last_rot
                    last_rot = master.rot
                    a = a + d
                    self.x = master.x + r*cos(a)
                    self.y = master.y + r*sin(a)
                    self.rot = base_rot + master.rot
                    task._Wait(1)
                end
            end)
            task._Wait(60)
            for _=1,_infinite do
                local rot0=(self.rot)
                do
                    local _beg_rot=rot0 local rot=_beg_rot local _end_rot=rot0 + 90 local _w_rot=0 local _d_w_rot=1/(120-1)
                    for _=1,120 do
                        self.rot=rot
                        task._Wait(1)
                        _w_rot=_w_rot+_d_w_rot if _w_rot<0.5 then rot=2*(_end_rot-_beg_rot)*_w_rot^2+_beg_rot else rot=(_end_rot-_beg_rot)*(-2*_w_rot^2+4*_w_rot-1)+_beg_rot end
                    end
                end
                task._Wait(60)
                PlaySound("kira00",0.5,self.x/256,true)
                local a0=(Angle(self,player))
                do
                    local _beg_a=a0 local a=_beg_a local _end_a=a0+360 local _d_a=(_end_a-_beg_a)/(90)
                    local _h_r=(60-(30))/2 local _t_r=(60+(30))/2 local r=_h_r*sin(-180)+_t_r local _w_r=-180 local _d_w_r=6*360/(90)
                    for _=1,90 do
                        last=New(_straight,grain_a,COLOR_PURPLE,self.x + r * cos(a), self.y + r * sin(a),1.5,a,false,0,true,true,0,false,0,0,0,false)
                        lasttask=task.New(last,function()
                            local self=task.GetSelf()
                            for _=1,12 do
                                if ran:Int(1,100)>=95 then
                                    last=New(_straight,ball_mid,COLOR_PURPLE,self.x,self.y,0.5,ran:Float(0, 360),false,0,true,true,0,false,0,0,0,false)
                                    lasttask=task.New(last,function()
                                        local self=task.GetSelf()
                                        task._Wait(300)
                                        _del(self,true)
                                    end)
                                end
                                task._Wait(5)
                            end
                        end)
                        a=a+_d_a
                        _w_r=_w_r+_d_w_r r=_h_r*sin(_w_r)+_t_r
                    end
                end
                do
                    local _beg_a=a0 local a=_beg_a local _end_a=a0+360 local _d_a=(_end_a-_beg_a)/(90)
                    local _h_r=(90-(30))/2 local _t_r=(90+(30))/2 local r=_h_r*sin(0)+_t_r local _w_r=0 local _d_w_r=6*360/(90)
                    for _=1,90 do
                        last=New(_straight,grain_a,COLOR_PURPLE,self.x + r * cos(a), self.y + r * sin(a),1.5,a,false,0,true,true,0,false,0,0,0,false)
                        lasttask=task.New(last,function()
                            local self=task.GetSelf()
                            for _=1,12 do
                                if ran:Int(1,100)>=95 then
                                    last=New(_straight,ball_mid,COLOR_PURPLE,self.x,self.y,0.5,ran:Float(0, 360),false,0,true,true,0,false,0,0,0,false)
                                    lasttask=task.New(last,function()
                                        local self=task.GetSelf()
                                        task._Wait(300)
                                        _del(self,true)
                                    end)
                                end
                                task._Wait(5)
                            end
                        end)
                        a=a+_d_a
                        _w_r=_w_r+_d_w_r r=_h_r*sin(_w_r)+_t_r
                    end
                end
                task._Wait(180)
            end
        end)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
    self.group=GROUP_ENEMY
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","莲台野「墓碑后的冥界」",_tmp_sc,#_editor_class["Aya"].cards,false})
_tmp_sc=boss.card.New("伊奘诺「神秘的具象」",50,50,50,1800,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        --[[ 这个弹设是两三年前的，所以写得非常烂，但莫名奇妙地产生了一种周期性变化，所以就不过多改动了
        ]]
        task.MoveTo(0,0,60,MOVE_ACC_DEC)
        local N=(10)
        local list=({})
        for i=1,N do
            list[i]=0
        end
        do local sign,_d_sign=(1),(1) for _=1,12 do
            do local n,_d_n=(1),(1) for _=1,N do
                last=New(_editor_class["sc5_slave"],self.x,self.y,n,sign%2,N,list)
            n=n+_d_n end end
            for _,unit in ObjList(GROUP_ENEMY) do
                lasttask=task.New(unit,function()
                    local self=task.GetSelf()
                    do
                        local _beg_r=20 local r=_beg_r local _end_r=120 local _d_r=(_end_r-_beg_r)/(120-1)
                        for _=1,120 do
                            self.r=r
                            task._Wait(1)
                            r=r+_d_r
                        end
                    end
                end)
            end
            task._Wait(120)
            for _,unit in ObjList(GROUP_ENEMY) do
                lasttask=task.New(unit,function()
                    local self=task.GetSelf()
                    do
                        local _beg_r=120 local r=_beg_r local _end_r=20 local _d_r=(_end_r-_beg_r)/(120-1)
                        for _=1,120 do
                            self.r=r
                            task._Wait(1)
                            r=r+_d_r
                        end
                    end
                end)
            end
            task._Wait(120)
            self.group=GROUP_GHOST
            for _,unit in ObjList(GROUP_ENEMY) do
                _kill(unit,true)
            end
            self.group=GROUP_ENEMY
        sign=sign+_d_sign end end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Aya"].cards,_tmp_sc)
table.insert(_sc_table,{"Aya","伊奘诺「神秘的具象」",_tmp_sc,#_editor_class["Aya"].cards,false})
stage.group.New('menu',{},"Normal",{lifeleft=7,power=400,faith=50000,bomb=3},true,1)
stage.group.AddStage('Normal','SpellCard@Normal',{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('SpellCard@Normal','init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(HM_hzc4_background)
        task._Wait(60)
        LoadMusicRecord("spellcard")
        _play_music("spellcard")
        local _boss_wait=true
        local _ref=New(_editor_class["Aya"],_editor_class["Aya"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
