---=====================================
---THLoOP Localization Dialog
---东方梦摇篮本土化 对话
---=====================================

local lib = aic.l10n.zh_cn.dialog

---boss前对话
lib.dialog1 = {
    pos = {
        'left',
        'left',
        'left',
        'left',
        'left',
        'left',
        'left',
        'right',
        'left',
        'left',
        'right',
        'left',
        'right',
        'right',
        'left',
        'left',
        'right',
        'right',
    },
    px = {
        80,
        80,
        80,
        80,
        80,
        80,
        80,
        380,
        80,
        80,
        380,
        80,
        380,
        380,
        80,
        80,
        380,
        380,
    },
    canskip = true,
    t = 120,
    hscale = 0.1,
    vscale = 0.1,
    vol = 1,
    name = {
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '宇佐见莲子',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '？？？',
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '射命丸文',
        '梅莉&莲子',
        '射命丸文？',
        '射命丸文？',
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '射命丸文？',
        '射命丸文？',
    },
    snd = nil,
    img = {
        "image:Maribel_face",
        "image:Renko_face_confused",
        "image:Maribel_face",
        "image:Renko_face_speechless",
        "image:Renko_face", 
        "image:Renko_face",
        "image:Maribel_face_happy",
        "image:Aya_face_hidden",
        "image:Maribel_face_surprise",
        "image:Renko_face_confused",
        "image:Aya_face_contempt",
        "image:Hiffu_face",
        "image:Aya_face",
        "image:Aya_face_contempt",
        "image:Maribel_face_speechless",
        "image:Renko_face_angry",
        "image:Aya_face",
        "image:Aya_face_contempt",
    },
    text = {
        '<color 0xFFE1CB65>没过一会地就到这里了呢。</color>',
        '<color 0xFF985C5B>从狭窄的隧道里出来后，\n就突然来到这样开阔的另一个世界。</color>',
        '<color 0xFFE1CB65>不知道为什么在穿梭的过程中获得了能够轻易\n使出的奇妙子弹，身边还飞着各种奇妙的……\n虫子还是什么东西。</color>',
        '<color 0xFF985C5B>……也许是所谓的「量子泡沫」的具象化吧。</color>',
        '<color 0xFF985C5B>幸好它们没沾到衣服上。</color>',
        '<color 0xFF985C5B>这里就是「现代」吗？\n历史通识课上学到过……</color>',
        '<color 0xFFE1CB65>和我们的学校很像呢。\n我要去那里看看……</color>',
        '啊呀呀呀呀？看来有稀客~',
        '<color 0xFFE1CB65>你是什么人？</color>',
        '<color 0xFF985C5B>……不是人类吧？\n这么大的翅膀。</color>',
        '幻想乡一流天狗记者，射命丸文……',
        '<color 0xFF985C5B>幻什么乡的，听都没听过。</color>\n<color 0xFFE1CB65>这里也不是很乡吧。</color>',
        '不过这里不是什么乡，\n我也不是射命丸文本人……',
        '这里是<scale 1.5>“邮电大学”，</scale>\n是一所以信息科技为特色、工学门类为主体、\n工管文理交叉融合的研究型大学，而我……',
        '<color 0xFFE1CB65></color 15>你在偷偷念纸条上的<scale 1.5></scale 4>百科词条吧！',
        '<color 0xFF985C5B>先别胡诌了！告诉我你究竟是谁，\n这里是哪里，以及怎么回去！</color>',
        '你们不是属于「现在」的人吧？我看出来了，\n你们的经历，正是很有价值的素材！',
        '你们想离开？\n得先好好「采访」你们才行！',
    },
}

---boss后对话（无续关）
lib.dialog2 = {
    pos = {
        'left',
        'left',
        'right',
        'right',
        'right',
        'left',
        'left',
        'right',
        'left',
        'left',
        'left',
    },
    px = {
        80,
        80,
        380,
        380,
        380,
        80,
        80,
        380,
        80,
        80,
        80,
    },
    canskip = true,
    t = 120,
    hscale = 0.1,
    vscale = 0.1,
    vol = 1,
    name = {
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '射命丸文？',
        '射命丸文之影',
        '射命丸文之影',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '射命丸文之影',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '玛艾露贝莉・赫恩',
    },
    snd = nil,
    img = {
        "image:Renko_face_happy",
        "image:Maribel_face_confused",
        "image:Aya_face_defeated",
        "image:Aya_face_defeated",
        "image:Aya_face_defeated",
        "image:Renko_face",
        "image:Maribel_face",
        "image:Aya_face_defeated_contempt",
        "image:Renko_face_suprise",
        "image:Maribel_face_confused",
        "image:Maribel_face_happy",
    },
    text = {
        '<color 0xFF985C5B>新能力意外地还挺好使的。\n好玩。</color>',
        '<scale 0.75></scale 31><color 0xFFE1CB65></color 31>（小声）为什么我仿佛看见了我们过去的经历？\n像是走马灯一样……',
        '你们的能力居然跟上了我的速度……\n我看你们绝非凡人，尤其是那个金头发的，\n很有天赋嘛……',
        '其实我也来自「另一个世界」，\n我是那个世界名叫「射命丸文」的记者的全息投影，\n拥有部分原来的思想和意识。',
        '我此次是根据她的指令，\n来到了这个世界（外界）收集不同的情报，\n为报纸提供新鲜的异世界风土见闻。',
        '<color 0xFF985C5B>所以你通过采访我们的「信息」，\n反过来与我们进行决斗……也许更像游戏？</color>',
        '<color 0xFFE1CB65>你会放电吗？那个经典电影的超级反派……</color>',
        '我又不是那条皇带鱼！\n我的采访任务已经结束了！再见！',
        '<color 0xFF985C5B>这一切都好奇异……无论是这里的环境\n还是这个……呃……更奇异的记者。</color>',
        '<color 0xFFE1CB65>不过这里有不一样的新鲜空气呢！</color>',
        '<color 0xFFE1CB65>在回去之前再玩一会吧！\n莲子，那里看起来有完全一样的塔哦……</color>',
    },
}

---boss后对话（续关）
lib.dialog3 = {
    pos = 'right',
    px = 380,
    canskip = true,
    t = 120,
    hscale = 0.1,
    vscale = 0.1,
    vol = 1,
    name = '射命丸文？',
    snd = nil,
    img = "image:Aya_face_contempt",
    text = {
        '感谢二位参与此次采访，后会有期~',
        '<scale 0.5>又收集到有趣的素材，可以交差了……<scale>',
    },
}

---staff名单
---staff
lib.staff = {
    { '东方xAliceInCradle 二次同人创作游戏', 'Thohou x AliceInCradle Fanmade Game' },
    { '东方梦摇篮', 'Thohou Lodestar of Oriental Paradise' },
    { '2025年八月', 'August, 2025' },
    { '主程序', 'Program', '苍木羽Muki', '喜报：程序异常警告.png' },
    { '部分音乐', 'Music', '灵空天仪', '……' },
    { 'UI设计', 'UI Design', '苍木羽Muki', '尽量往原作上靠了（' },
    { '弹幕设计', 'Danmaku Design', '苍木羽Muki', '现在不敢说比th20强了' },
    { '文案', 'Copywriting', '苍木羽Muki', '曾经也是同人文写手' },
    { '游戏制作工具', 'Game Making Tools', 'LuaSTG aex+\n\nLuaSTG Editor Sharp' },
    { '特别支持', 'Special Support', '绀念雪Nenyuki', '早点睡啊你这家伙' },
    { '特别支持', 'Special Support', '某人', '留这句话前一天没有收到生日礼物' },
    { '特别感谢', 'Speical Thanks', '东方Project原作者\n\nZun' },
    { '特别感谢', 'Speical Thanks', 'AliceInCradle原作者\n\nひなゆあ  桥野みずは' },
    { '特别感谢', 'Speical Thanks', '还有您!', 'And You!' },
    { '恭喜通关！', 'Thanks for Playing!' },
}
