---=====================================
---THLoOP Localization Dialog
---东方梦摇篮本土化 对话
---=====================================

local lib = aic.l10n.zh_cn.dialog

---boss前对话
lib.dialog1 = {
    pos = {
        'left',
        'left',
        'left',
        'left',
        'left',
        'left',
        'left',
        'right',
        'left',
        'left',
        'right',
        'left',
        'right',
        'right',
        'left',
        'left',
        'right',
        'right',
    },
    px = {
        80,
        80,
        80,
        80,
        80,
        80,
        80,
        380,
        80,
        80,
        380,
        80,
        380,
        380,
        80,
        80,
        380,
        380,
    },
    canskip = true,
    t = 120,
    hscale = 0.2,
    vscale = 0.2,
    vol = 1,
    name = {
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '宇佐见莲子',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '？？？',
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '射命丸文',
        '梅莉&莲子',
        '射命丸文？',
        '射命丸文？',
        '玛艾露贝莉・赫恩',
        '宇佐见莲子',
        '射命丸文？',
        '射命丸文？',
    },
    snd = nil,
    img = {
        "image:Maribel_face",
        "image:Renko_face_confused",
        "image:Maribel_face",
        "image:Renko_face_speechless",
        "image:Renko_face", 
        "image:Renko_face",
        "image:Maribel_face_happy",
        "image:Aya_face_hidden",
        "image:Maribel_face_surprise",
        "image:Renko_face_confused",
        "image:Aya_face_contempt",
        "image:Hiffu_face",
        "image:Aya_face",
        "image:Aya_face_contempt",
        "image:Maribel_face_speechless",
        "image:Renko_face_angry",
        "image:Aya_face",
        "image:Aya_face_contempt",
    },
    text = {
        '<color 0xFFE1CB65>没过一会地就到这里了呢。</color>',
        '<color 0xFF985C5B>从狭窄的隧道里出来后，\n就突然来到这样开阔的另一个世界。</color>',
        '<color 0xFFE1CB65>不知道为什么在穿梭的过程中获得了能够轻易\n使出的奇妙子弹，身边还飞着各种奇妙的……\n虫子还是什么东西。</color>',
        '<color 0xFF985C5B>……也许是所谓的「量子泡沫」的具象化吧。</color>',
        '<color 0xFF985C5B>幸好它们没沾到衣服上。</color>',
        '<color 0xFF985C5B>这里就是「现代」吗？\n历史通识课上学到过……</color>',
        '<color 0xFFE1CB65>和我们的学校很像呢。\n我要去那里看看……</color>',
        '啊呀呀呀呀？看来有稀客~',
        '<color 0xFFE1CB65>你是什么人？</color>',
        '<color 0xFF985C5B>……不是人类吧？\n这么大的翅膀。</color>',
        '幻想乡一流天狗记者，射命丸文……',
        '<color 0xFF985C5B>幻什么乡的，听都没听过。</color>\n<color 0xFFE1CB65>这里也不是很乡吧。</color>',
        '不过这里不是什么乡，\n我也不是射命丸文本人……',
        '这里是<scale 1.5>“邮电大学”，</scale>\n是一所以信息科技为特色、工学门类为主体、\n工管文理交叉融合的研究型大学，而我……',
        '<color 0xFFE1CB65></color 15>你在偷偷念纸条上的<scale 1.5></scale 4>百科词条吧！',
        '<color 0xFF985C5B>先别胡诌了！告诉我你究竟是谁，\n这里是哪里，以及怎么回去！</color>',
        '你们不是属于「现在」的人吧？我看出来了，\n你们的经历，正是很有价值的素材！',
        '你们想离开？\n得先好好「采访」你们才行！',
    },
}

---boss后对话（无续关）
lib.dialog2 = {
    pos = {
        'left',
        'left',
        'right',
        'right',
        'right',
        'left',
        'left',
        'right',
        'left',
        'left',
        'left',
    },
    px = {
        80,
        80,
        380,
        380,
        380,
        80,
        80,
        380,
        80,
        80,
        80,
    },
    canskip = true,
    t = 120,
    hscale = 0.2,
    vscale = 0.2,
    vol = 1,
    name = {
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '射命丸文？',
        '射命丸文之影',
        '射命丸文之影',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '射命丸文之影',
        '宇佐见莲子',
        '玛艾露贝莉・赫恩',
        '玛艾露贝莉・赫恩',
    },
    snd = nil,
    img = {
        "image:Renko_face_happy",
        "image:Maribel_face_confused",
        "image:Aya_face_defeated",
        "image:Aya_face_defeated",
        "image:Aya_face_defeated",
        "image:Renko_face",
        "image:Maribel_face",
        "image:Aya_face_defeated_contempt",
        "image:Renko_face_suprise",
        "image:Maribel_face_confused",
        "image:Maribel_face_happy",
    },
    text = {
        '<color 0xFF985C5B>新能力意外地还挺好使的。\n好玩。</color>',
        '<scale 0.75></scale 31><color 0xFFE1CB65></color 31>（小声）为什么我仿佛看见了我们过去的经历？\n像是走马灯一样……',
        '你们的能力居然跟上了我的速度……\n我看你们绝非凡人，尤其是那个金头发的，\n很有天赋嘛……',
        '其实我也来自「另一个世界」，\n我是那个世界名叫「射命丸文」的记者的全息投影，\n拥有部分原来的思想和意识。',
        '我此次是根据她的指令，\n来到了这个世界（外界）收集不同的情报，\n为报纸提供新鲜的异世界风土见闻。',
        '<color 0xFF985C5B>所以你通过采访我们的「信息」，\n反过来与我们进行决斗……也许更像游戏？</color>',
        '<color 0xFFE1CB65>你会放电吗？那个经典电影的超级反派……</color>',
        '我又不是那条皇带鱼！\n我的采访任务已经结束了！再见！',
        '<color 0xFF985C5B>这一切都好奇异……无论是这里的环境\n还是这个……呃……更奇异的记者。</color>',
        '<color 0xFFE1CB65>不过这里有不一样的新鲜空气呢！</color>',
        '<color 0xFFE1CB65>在回去之前再玩一会吧！\n莲子，那里看起来有完全一样的塔哦……</color>',
    },
}

---boss后对话（续关）
lib.dialog3 = {
    pos = 'right',
    px = 380,
    canskip = true,
    t = 120,
    hscale = 0.2,
    vscale = 0.2,
    vol = 1,
    name = '射命丸文？',
    snd = nil,
    img = "image:Aya_face_contempt",
    text = {
        '感谢二位参与此次采访，后会有期~',
        '<scale 0.5>又收集到有趣的素材，可以交差了……<scale>',
    },
}

---staff名单
---staff
lib.staff = {
    { '东方Projectx北京邮电大学\n二次同人创作游戏', '\n\nThohou x BUPT Fanmade Game' },
    { '秘封采访之旅', 'Yuri interview with supernatural club.' },
    { '2026年九月', 'September, 2026' },
    { '主催/弹幕设计', 'Danmaku Design', '路人明ing', '梅丽可爱！莲子可爱！大家可爱！\nGPT vs LuaSTG，你们知道吗？' },
    { '主程序/UI设计/弹幕设计', 'Programming/UI Design/Danmaku Design', '苍木羽Muki', '好好睡，好好睡\n大肥鱼能不能少吃点白饭' },
    { '自机设计/弹幕设计', 'Player Design/ Danmaku Design', 'Ichirinko', '秘封组什么时候结婚\n游戏难度太大就骂我（' },
    { '弹幕设计', 'Danmaku Design', '千东万方', '' },
    { '音乐', 'Music', 'y的自然对数', '第一次做，希望下次能做好一点（' },
    { '剧情', 'Story', '雾雨65535香蛋', '你说得对，但是蓝原椿是一个态度冷淡、\n有些S属性的乖僻女后面忘了' },
    { '立绘绘制', 'Standing Illustrating', 'choco', '北京的饭好难吃' },
    { '行走图绘制', 'WalkImage Illustrating', 'Downloading', '' },
    { 'UI绘制', 'UI Illustrating', 'sikr', '我觉得臭臭说的对，北京的饭好难吃\nui里面私货给我塞爽了，大大方方乱画小人的来' },
    { '宣传海报设计', 'Publicity Poster Design', '雾雨霁翎', '' },
    { '概念设计', 'Conceptual Design', '鹿关王HapyI', '好想吃滨寿司啊——\n顺带一提紫大人很可爱\n设计的东方忏悔加有没有懂的' },
    { '游戏开发工具', 'Game Developing Tools', 'LuaSTG aex+\n\nLuaSTG Editor Sharp' },
    { '特别支持', 'Special Support', '绀念雪Nenyuki', '早点起啊你这家伙' },
    { '特别支持', 'Special Support', 'イクチュ', '可以跟我组一辈子符卡吗？' },
    { '特别支持', 'Special Support', '东方梦摇篮', '代码复用救大命了' },
    { '特别支持', 'Special Support', 'DeepSeek Claude ChatGPT...', 'Vibe coding是对的' },
    { '特别感谢', 'Special Thanks', '东方Project原作者\n\nZun' },
    { '特别感谢', 'Special Thanks', '北邮东方同好会全部成员\n各校帮助者\nAnd You!' },
    { '恭喜通关！', 'Thanks for Playing!' },
}
